### ISSUE TITLE
please provide debian and ubuntu packages

### ISSUE THREAD

**Issue by COLABORATI** [beave/sagan#101]
please provide debian and ubuntu packages

**Comment by beave** [comment]
Debian/ubuntu packages have been provide in the past but are likely out of date.  The maintainer (Pierre Chifflier <pollux@debian.org>) hasn't updated them in sometime.   He is a very busy guy! :)

If you'd likely to step up and possibly take this role over,  that would be great.  In the mean time, I simply do not have enough time to do them myself.  I will continue to look for other maintainers.
