### ISSUE TITLE
BroIntel Address Loading

### ISSUE THREAD

**Issue by CyberTaoFlow** [beave/sagan#104]
I found that in the current master every single address item in a brointel file was being seen as a duplicate leading to zero IP's being loaded.  

I was able to resolve this issue by inverting the check:

diff --git a/src/processors/bro-intel.c b/src/processors/bro-intel.c
index ff20ade..3accf16 100644
--- a/src/processors/bro-intel.c
+++ b/src/processors/bro-intel.c
@@ -239,7 +239,7 @@ void Sagan_BroIntel_Load_File ( void )
                                     for (i=0; i < counters->brointel_addr_count; i++)
                                         {
 
-                                            if ( memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
+                                            if (!memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
                                                 {
                                                     Sagan_Log(S_WARN, "[%s, line %d] Got duplicate Intel::ADDR address %s in %s on line %d.", __FILE__, __LINE__, value, brointel_filename, line_count + 1);

**Comment by CyberTaoFlow** [comment]
`diff --git a/src/processors/bro-intel.c b/src/processors/bro-intel.c
index ff20ade..3accf16 100644
--- a/src/processors/bro-intel.c
+++ b/src/processors/bro-intel.c
@@ -239,7 +239,7 @@ void Sagan_BroIntel_Load_File ( void )
                                     for (i=0; i < counters->brointel_addr_count; i++)
                                         {
 
-                                            if ( memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
+                                            if (!memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
                                                 {
                                                     Sagan_Log(S_WARN, "[%s, line %d] Got duplicate Intel::ADDR address %s in %s on line %d.", __FILE__, __LINE__, value, brointel_filename, line_count + 1);
`

**Comment by CyberTaoFlow** [comment]
> diff --git a/src/processors/bro-intel.c b/src/processors/bro-intel.c
index ff20ade..3accf16 100644
--- a/src/processors/bro-intel.c
+++ b/src/processors/bro-intel.c
@@ -239,7 +239,7 @@ void Sagan_BroIntel_Load_File ( void )
                                     for (i=0; i < counters->brointel_addr_count; i++)
                                         {
 
-                                            if ( memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
+                                            if (!memcmp(Sagan_BroIntel_Intel_Addr[i].bits_ip, bits_ip, sizeof(bits_ip)) )
                                                 {
                                                     Sagan_Log(S_WARN, "[%s, line %d] Got duplicate Intel::ADDR address %s in %s on line %d.", __FILE__, __LINE__, value, brointel_filename, line_count + 1);

**Comment by beave** [comment]
Thanks.  This has been resolved.  Please let me know if you run into anything else!
