### ISSUE TITLE
Adding normalization types

### ISSUE THREAD

**Issue by srawls1740** [beave/sagan#106]
Please add in additional normalization types. It would be nice to see mac for MAC addresses as well as a generic string type.

**Comment by CyberTaoFlow** [comment]
Umm that is easily added as it's already supported by liblognorm the underlying normaliztion library as mac48 and string respectively.

**Comment by beave** [comment]
CyberTaoFlow is correct.  It's easy too add.  However,  what do you want to do with it?  Threshold/after by MAC?  Right now,  if I added it,  it would be part of the JSON for liblognorm.  That might be useful with "external",  but internally to Sagan,  it won't really "do" anything with the data.

Let me know your thoughts and thanks.

**Comment by srawls1740** [comment]
Just wanted it for use with external, which is in the latest version. Thanks!
