### ISSUE TITLE
Rule with a lot of flows fails... 

### ISSUE THREAD

**Issue by beave** [beave/sagan#113]
As per discussion at https://groups.google.com/forum/#!topic/sagan-users/og8cc6p6iN0

**Comment by beave** [comment]
System throws errors then segfaults.  Here's the rule:

alert ip [101.69.247.42,101.74.21.117,101.81.126.10,101.81.131.55,101.81.184.66,101.81.191.5,101.81.2.22,101.81.22.253,101.81.71.49,101.87.2.167,101.89.66.218,101.93.104.251,101.95.171.230,101.95.1.82,101.96.134.166,101.96.46.187,101.98.78.60,102.165.211.63,103.10.151.146,103.10.87.50,103.1.224.146,103.101.57.210,103.101.89.196,103.103.216.76,103.104.232.237,103.105.190.250,103.105.49.139,103.106.22.3,103.107.151.13,103.107.63.236,103.107.8.81,103.108.45.60,103.111.218.14,103.13.221.159,103.13.221.26,103.13.222.16,103.13.63.22,103.15.104.72,103.15.105.111,103.193.202.114,103.194.88.12,103.196.233.35,103.196.53.131,103.196.53.134,103.199.8.24,103.20.249.94,103.203.229.43,103.203.92.186,103.204.167.9,103.205.134.18] any -> $HOME_NET any (msg:"ET Indicator"; reference:url,www.cinsscore.com; reference:url,www.networkcloaking.com/cins; threshold: type limit, track by_src, seconds 3600, count 1; classtype:misc-attack; sid: 2; rev:40639;)

**Comment by msnriggs** [comment]
It looks like if spaces are put in the IP array after the commas, the error resolves. ex [1.1.1.1,2.2.2.2,3.3.3.3] vs [1.1.1.1, 2.2.2.2, 3.3.3.3].

**Comment by beave** [comment]
Errr.. that's weird.  Does it also resolve the segfault as well?  Also,  what version of Sagan are you running.  Thanks!

**Comment by beave** [comment]
This should be fixed.  You'll want to pull down the latest code from Github.   If you're using prior/older code,  it will likely "load" but not actually work.   This fix allows you to load up those lists via the "alert ip" type.  

Also,  this issue is sort of involved with this: 

https://groups.google.com/forum/#!topic/sagan-users/RwSvWHUaAt4

Long story short,  get the latest release and test with that.   Otherwise,  it's likely not working.

**Comment by beave** [comment]
I dont think is 100% fixed.  I'll look at it today.

**Comment by msnriggs** [comment]
I am running Sagan version 1.1.9-git

I will pull back down and recompile

**Comment by msnriggs** [comment]
Still seeing the issue on a newly compiled version

**Comment by beave** [comment]
Same issue,  as in the error is back or it's not working?

I'll look ASAP.

**Comment by msnriggs** [comment]
Same issue as in I am still getting the seg fault while loading the ruleset

**Comment by beave** [comment]
Oh!  I got it to load but let me test again.  Thanks On Jun 4, 2018 5:02 PM, msnriggs <notifications@github.com> wrote:Same issue as in I am still getting the seg fault while loading the ruleset

**Comment by beave** [comment]
Hey - it doesn't segfault for me but it doesn't work either.  Would you mind re-pasting the rule that causes yours to segfault and also try against the latest github.com.  I want to make sure that we are synced.

Also - This is an emerging threat rule,  not a Sagan rule.  You're going to want to add "parse_src_ip: 1; parse_dst_ip: 2;" to the rule (so it can parse out the IP addresses of the log message and apply it to the HOME_NET/EXTERNAL_NET rule option at the beginning). 

Thank and I'll keep looking.

**Comment by beave** [comment]
This is going to take a bit more work.  It should function under 1.1.6 but i think i'm going to have to re-work the code with the IPv6 updates.  I'll let you know how it goes.

**Comment by beave** [comment]
Hey - this has been fixed.  Again, you'll need normalization from liblognorm or parse_src_ip to grab the IP's.  It's working fine in testing now! :)

**Comment by beave** [comment]
Since I haven't heard anything and my testing shows this working now,  i'm going to close this.  Thank you for reporting it and place let me know if you run into any other issues.

**Comment by msnriggs** [comment]
Sorry Champ, yes, it looks resolved now. My apologies, I appreciate your
project!
