### ISSUE TITLE
Duplicate rule file in sagan.yaml

### ISSUE THREAD

**Issue by msnriggs** [beave/sagan#118]
**Describe the bug**
$RULE_PATH/windows-security.rules is duplicated on line 697 and 701 of sagan.yaml, resulting duplicate rules errors loading sagan when compiled from repo, causing sagan to fail to start.

**To Reproduce**
Load sagan.yaml from github repo and load

**Expected behavior**
Either error handling for duplicate rules or removing the duplicate from the yaml file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser N/A
 - Version 1.2.1-git

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beave** [comment]
Thank you!  Fixed!
