### ISSUE TITLE
Full logging to eve.json

### ISSUE THREAD

**Issue by msnriggs** [beave/sagan#119]
**Is your feature request related to a problem? Please describe.**
Full logging to eve.json for all events that come through the FIFO pipe, the sagan.yaml option is available, but as noted isn't implemented yet.

**Describe the solution you'd like**
Full logging to eve.json for all events that come through the FIFO pipe, the sagan.yaml option is available, but as noted isn't implemented yet.

**Describe alternatives you've considered**
I am unsure of any other way to pull all events, not just alerts into eve.json.

**Additional context**

**Comment by beave** [comment]
Hello, 

This hasn't been implemented yet but was something I had thought about. I was unsure how useful it might be.   The one use case I had was the ability for Sagan to write out all events in a json format (like Suricata) and then have something like Logstash "slurp" it up.  In our production env. we have the syslog daemon recording to regular log files and the Sagan FIFO.   The standard log files allow easy access for reviewing. 

I'd be interested in your use cases/thoughts.

**Comment by msnriggs** [comment]
Consumption with logstash is the exact use case I had in mind. It would be
extremely useful to leverage existing facilities already forwarding data
off in lieu of building something new to send the data to the same location.

Mike

**Comment by beave** [comment]
Yes.  I think this is definitely worth doing.   It shouldn't be to bad.  Is there any particular format you think the data should be in?  I was thinking it would have a flow_id,  type,  etc (similar to Suricata) well as all syslog fields (message, date, time, program, etc).

**Comment by beave** [comment]
Here's my mock-up's for output. Let me know what you think:

This first one is when data is parsed by built in functions (parse_src_ip, parse_dst_ip, etc):  Hence the "parsed_data:"

{"timestamp":"2018-06-27T17:17:07.000454+0000","flow_id":168885737688523,"event_type":"logs","syslog_source":"192.168.1.1","syslog_port":514,"syslog_proto":"UDP","facility":"local7","priority":"warning","level":"warning","tag":"bc","source_timestamp":"2018-06-27 14:49:30","program":"named","message":"Invalid login for bob from 192.168.2.1:1000 to 192.168.2.2:22 proto tcp", "parsed_data":{"src-ip":"192.168.2.1","src-port":1000,"dst-ip":"192.168.2.2",dst-port:22,"proto":"TCP"}}

This is data normalized via Liblognorm:

{"timestamp":"2018-06-27T17:17:07.000454+0000","flow_id":168885737688524,"event_type":"logs","syslog_source":"192.168.1.1","syslog_port":514,"syslog_proto":"UDP","facility":"local7","priority":"warning","level":"warning","tag":"bc","source_timestamp":"2018-06-27 14:49:30","program":"named","message":"Invalid login for bob from 192.168.2.1:1000 to 192.168.2.2:22 proto tcp", "normalized_data":{"src-ip":"192.168.2.1","src-port":1000,"dst-ip":"192.168.2.2",dst-port:22,"proto":"TCP","username":"bob"}}

**Comment by msnriggs** [comment]
I think it makes sense to match up Suricata field names where prudent and then extend with the syslog specific fields like you described above - I like the mockup. Dragging the liblognorm data I think give better field options and further parsing.

**Comment by beave** [comment]
Hah! So I was looking at the configuration:

  - eve-log:
      enabled: no
      filetype: regular            #regular|syslog|unix_dgram|unix_stream|redis
      interface: logs
      alerts: yes                     # Logs alerts
      logs: no                        # Log everything
      filename: "$LOG_PATH/eve.json"

Note the "logs: no" (that's what we're implementing now!).  See,  told you I had thought of it before! :)

**Comment by msnriggs** [comment]
Exactly, that's why I figured I would formalize the request since you had made the note above that only lerts and filetype: regular are supported.

**Comment by beave** [comment]
Okay.  I just committed this.  If you set "logs" to "yes" or "enabled" it will stream all logs to the eve file.  In order for normalization to really happen,  at least one rule has to have the "normalize;" option in it.  If normalization isn't on,  the liblognorm json value will be "null".  I dont see this being a big deal.

Alerts are stored as event_type "alert" and logs are stored as event_type "log".

I think this is pretty cool.  Let me know how it works out for you and if you hit any snags! Oh,

**Comment by msnriggs** [comment]
First run is looking good!

**Comment by beave** [comment]
Cool!  I did notice a memory leak (im not freeing the JSON object).  I've got the fix already for it, but it hasn't been committed yet.   It's not a huge leak,  but over time it could cause issues. 

I'll let you know when its up.

**Comment by msnriggs** [comment]
Sounds good, I will clone and recompile when it is up.

**Comment by beave** [comment]
I think this is all done now.   I forgot to post here.  

I'm going to go ahead and close this but please let me know if you have any issues pop up!

Thank you!
