### ISSUE TITLE
!10.10.10.10/24 isn't working in HOME/EXTERNAL positions.

### ISSUE THREAD

**Issue by beave** [beave/sagan#123]
This won't work...   I think ! is broken...

alert any [!10.10.10.10/32] any -> $HOME_NET any (msg: "Champtest"; content: "champtest"; parse_src_ip: 1; parse_dst_ip: 2;  classtype: successful-user; sid: 8070010; rev:1;)

**Comment by red8383light** [comment]
[for_sagan.zip](https://github.com/beave/sagan/files/2898584/for_sagan.zip)
I have made the fix's for this issue and included them in the zip file.

**Comment by beave** [comment]
I tested this the other day and it was working.   I'm going to close this out for now.
