### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by Penguin-Guru** [beave/sagan#128]
Hi, I've been trying to find answers to a couple questions/concerns. Please answer when you can, or tell me where to look.

First: I am concerned that the logs modified by default settings (default-host, default-port, and default-proto) will be ambiguous and potentially misleading in some cases when operating on remote logs from multiple servers on different networks. I thought to set the values to something obviously invalid, like 0.0.0.0:0, but it seems you have checks in place to specifically prevent this. Could you tell me why? If it is not necessary, I will simply remove the checks. If it is necessary, what should I do to eliminate the ambiguity?

Second: I understand this is not what Sagan (or Snort) is designed for, but I would like to have alert rules in place for log entries that have not been matched by any other/preceeding rule (behaviour similar to LogCheck). I found a rule format that supposedly works for Snort, but before trying it I would like to understand what exactly 'drop' rules do in Sagan. In Snort they drop the packet, but in Sagan do they prevent parsing by proceeding rules or do they issue a signal to Snortsam? It would also be helpful to know if rules are not parsed in the same order as Snort.

Again, sorry for posting this as an issue here but I'm not sure what else to do. I have been in your IRC channel for several days and I can't figure out how to use your mailing list without a Google account.

**Comment by Penguin-Guru** [comment]
First: I noticed that localhost addresses are also changed to default-host. Guessing Sagan was intended to be run on local logs. I will try patching these bits out and see if it breaks anything obvious. I also noticed that there seems to be a protocol type 'syslog' in "rules.c". Is this intended for remote logs?

Second: My limited testing suggests that both alert and drop rules are stored in their declared order (at least per file); and that drop rules effectively negate preceding alerts, but not subsequent. Is this right? I have yet to test the order in which files are loaded. One odd quirk is that, when I dropped an identical rule immediately before alerting, the alert was output with the drop rule's sid code. Seems like I'm still missing something...

**Comment by Penguin-Guru** [comment]
Not sure if anyone is actually reading this but here's what I did: https://github.com/Penguin-Guru/sagan/commit/bdc100cfd732017b3e5dc7cdd15c3542ec684319

It seems to be working so far, but I'm sure there are some bad ideas sprinkled in.

Still not 100% sure about the drop rules.

**Comment by beave** [comment]
Sorry for the delay.  The Sagan mailing list is probably best for this sort of stuff.  There is a link off hte main Sagan website and it can be found here:  https://groups.google.com/forum/#!forum/sagan-users

The "drop" rule option simply marks the rule to be dropped.  That is,  Sagan doesn't internally "do" anything with it.  The output (EVE, etc) will specify that it should be dropped.  Its up to an external program,  like "Meer" to do the actual dropping. 

On the "localhost" and "127.0.0.1" issue.  Sagan will attempt to "normalize" IP addresses out of the logs.   For example: 

If my syslog source is 192.168.1.1 and my log is this....

"invalid login from 12.12.12.12".  Sagan will normalize that "192.168.1.1" had a "invalid" login from "12.12.12.12". Now consider this:

"invalid login from 127.0.0.1".  Every machine in the network has a "127.0.0.1" address, so this data is useless. However,  we do know that the log came from "192.168.1.1".  If that machine is _reporting_ the log,  _it_ is probably the source of that bad login.  Sagan then replaces "127.0.0.1" with the IP address of 192.168.1.1. 

Sagan can sometimes determine protocols via the program or messages.  This is done via the "protocol.map" file.  For example,  if the program is "sshd",  we can assume that this log message will be related to TCP traffic,  hence mark it as TCP. 

I hope this helps and sorry for the delay.   If you have any other questions,  let's move them to the Sagan mailing list.   Also,  the Sagan documentation might help (its still a work in progress).

https://sagan.readthedocs.io/en/latest/

**Comment by Penguin-Guru** [comment]
Ok. No worries about the delay, thanks for responding. Is there any way to use the mailing list without a gmail account? I really did try to figure that out...

**Comment by beave** [comment]
I think you can sign up on the mailing list without a gmail account.   I'm pretty sure i've seen non-gmail accounts on the list before.
