### ISSUE TITLE
autogen expecting './README'?

### ISSUE THREAD

**Issue by Penguin-Guru** [beave/sagan#130]
Output from `./autogen.sh` is below. Guessing this is related to https://github.com/beave/sagan/commit/50bee822e67c6c0e81599508835f947b5b20d3ae; and generated by whatever code makes "missing", which also references the file "README". I haven't yet been able to figure out where this requirement is specified. You might also consider changing the references in "INSTALL" (https://github.com/Penguin-Guru/sagan/commit/67fb0ddb40705101c3e823e195bdffc71dcdc9d6).

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --include=m4 --force
autoreconf: running: /usr/bin/autoheader --include=m4 --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:9: installing './compile'
configure.ac:8: installing './config.guess'
configure.ac:8: installing './config.sub'
configure.ac:234: installing './install-sh'
configure.ac:234: installing './missing'
Makefile.am: error: required file './README' not found
src/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

**Comment by beave** [comment]
Thank you!  Totally missed that.
