### ISSUE TITLE
routing.c won't compile

### ISSUE THREAD

**Issue by rfoster55** [beave/sagan#132]
routing.c won't compile due to mis-structured preprocessor statements involving 
`#ifdef WITH_BLUEDOT`
and
`#ifdef HAVE_LIBMAXMINDDB`

The problem is that the removed code included opening braces, but not the corresponding closing braces.  Easy fix, but I can do a pull request if you want.

**To Reproduce**
Try to compile routing.c

**Expected behavior**

**Screenshots**
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I/usr/include/libfastjson    -g -O2 -D__Linux__ -MT sagan-routing.o -MD -MP -MF .deps/sagan-routing.Tpo -c -o sagan-routing.o `test -f 'routing.c' || echo './'`routing.c
routing.c:101:33: error: expected identifier or ‘(’ before ‘}’ token
                                 }
                                 ^
routing.c:102:25: error: expected identifier or ‘(’ before ‘}’ token
                         }
                         ^
routing.c:103:17: error: expected identifier or ‘(’ before ‘}’ token
                 }
                 ^
routing.c:104:9: error: expected identifier or ‘(’ before ‘}’ token
         }
         ^
routing.c:107:5: error: expected identifier or ‘(’ before ‘return’
     return(ret);
     ^~~~~~
routing.c:109:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^

**Comment by beave** [comment]
This should be resolved.  Thank you. Please re-open if it is not....
