### ISSUE TITLE
Alerts never trigger if WITH_BLUEDOT not defined

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#137]
**Describe the bug**
Alerts never trigger if WITH_BLUEDOT is not defined

**To Reproduce**
Configure/build without bluedot.  Then:
```
echo "192.0.2.1|local0|info|info|sshd|2001-01-01|00:00:00|sshd|User ubuntu not allowed because shell /etc/passwd is not executable" >/var/sagan/fifo/sagan.fifo
```

**Expected behavior**
Alert to be triggered

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
In `src/routing.c`, function `Sagan_Check_Routing()` always returns False if WITH_BLUEDOT is not defined.

Simple 2-line fix is possible:

```
--- a/src/routing.c
+++ b/src/routing.c
@@ -93,6 +93,8 @@ bool Sagan_Check_Routing(  _Sagan_Routing *SaganRouting )
                                                                                         }
                                                                                 }
                                                                         }
+#else
+                                                                   ret = true;
 #endif
                                                                 }
                                                         }
```

But IMO it would be better to change the existing logic from deeply-nested to flat.

**Comment by beave** [comment]
Should be resolved now.  Thank you
