### ISSUE TITLE
Concern around 'match' logic

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#139]
**Describe the bug**
The match logic in [src/processors/engine.c](https://github.com/beave/sagan/blob/master/src/processors/engine.c#L441) seems broken, since each test can cause the result of the previous test to be forgotten.

They are tested in the order:
* program
* syslog_facility
* syslog_level
* syslog_tag
* syslog_priority

But a later successful match overrides a previous failure.

**To Reproduce**
Have a rule like `program: sshd; syslog_facility: info`

This will match any message with syslog_facility info, regardless of whether the program is sshd or not.

Have a rule like `syslog_facility: mail; syslog_level: error`

This will match any message with syslog level error, regardless of whether the facility is mail or not.

**Expected behavior**
All conditions need to match.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
It's easier to think about the logic if you rename this variable in your head to "failed" or "unmatched".

While testing this I found another bug which is that the syslog match attributes are never tested anyway (#141), which means this issue is moot until that is fixed first.

**Comment by candlerb** [comment]
After #142 is applied, you can demonstrate the issue like this:

```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "GOTCHA"; content: "abcde"; classtype: unsuccessful-user; program: sshd; syslog_facility: mail; sid: 911; rev: 1; )
```

```
echo "192.0.2.1|mail|info|info|postfix|2001-01-01|00:00:00|postfix|abcde" >/var/sagan/fifo/sagan.fifo
```

```
[D] [processors/engine.c, line 1548] **[Trigger]*********************************
[D] [processors/engine.c, line 1549] Program: postfix | Facility: mail | Priority: info | Level: info | Tag: postfix
[D] [processors/engine.c, line 1550] Threshold flag: 0 | After flag: 0 | Flexbit Flag: 0 | Flexbit status: 0
[D] [processors/engine.c, line 1551] Triggering Message: abcde
```

(Triggers even though `program: sshd` has been specified)

**Comment by beave** [comment]
AH!  okay.. I was looking at the pull and didn't understand.  This explains things. Thank you. 

Let me review/test.
