### ISSUE TITLE
Rule parsing silently allows unrecognised conditions

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#140]
**Describe the bug**
A mis-typed or not-understood rule element is silently accepted.

**To Reproduce**
```
alert any $EXTERNAL_NET any -> $HOME_NET any (msg: "GOTCHA"; content: "abcde"; classtype: unsuccessful-user; womble: bomble; sid: 911; rev: 1; )
```

This triggers on the pattern abcde, despite the unknown condition `womble: bomble;`

**Expected behavior**
Rule to be skipped with a warning (as happens if `rev` is missing, for example) - or at least a warning to be emitted, even if the rule is kept.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by beave** [comment]
This has been a known issue for a while.  I'm going to leave this open.  It likely requires re-working the rules.c

**Comment by beave** [comment]
Took some time to address this.   It now checks rule options and is a good bit more aggressive on validating rules.  I'm going to go ahead and close this as I think we are in better shape.
