### ISSUE TITLE
sagan silently changes ownership of fifo

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#145]
**Describe the bug**
If sagan is started as root, it changes the ownership of its fifo to the uid and gid of the "sagan" user.

**To Reproduce**

```
# chown syslog:sagan /var/sagan/fifo/sagan.fifo
# sagan
^C
# ls -l /var/sagan/fifo/sagan.fifo
```

Its ownership has been changed from `syslog:sagan` to `sagan:sagan`

This change of ownership takes place in function `Droppriv()` in [src/utils.c](https://github.com/beave/sagan/blob/master/src/util.c#L123)

**Expected behavior**
I expected the permissions to be left alone.  I had carefully set the permissions to allow rsyslog to write to the fifo and sagan to read from it (mode 644, owner syslog, group sagan), and this work was undone.

I do not think it's a good idea to change the ownership of the fifo in this way.  I think it's the responsibility of whoever creates the fifo also to set the correct permissions.  For example, see [extra/RPM/sagan-setup.libexec](https://github.com/beave/sagan/blob/master/extra/RPM/sagan-setup.libexec#L21) - it creates the fifo, it sets the mode - it should also set the owner/group.

This changing of ownership doesn't even ensure security.  For example: if the fifo had been created with mode 666, then it would still be world-readable and world-writeable, and changing the owner and group doesn't correct that.

**Workaround**
I *could* have added the `syslog` user to supplementary group `sagan` and changed the fifo mode to 664.  I didn't want to do this as it opens up all sorts of issues.

In the end, I changed my systemd unit file to start sagan directly as the `sagan` user.  If sagan starts as uid !=0 it skips this code.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by beave** [comment]
I agree.  This was a work around from "issues" years ago about Sagan not being able to open the FIFO on a HUP.    IMO:  a) This should be a config options b) Shoulnd't be silent.  I'll correct this ASAP.

**Comment by beave** [comment]
Let's try this...  I have a new configuration option called "chown-fifo".  When enabled,  it will change the FIFO permissions.   If disabled, it will leave them in place.   When enabled,  it informs the user that the FIFO perms have changed.. Like this:

[*] Changing FIFO '/var/sagan/sagan.fifo' ownership to 'sagan'.
[*] Dropping privileges! [UID: 1007 GID: 1007]

I think this will do it.   Leaving open as it needs more testing.

**Comment by beave** [comment]
I'm going to close this. I think we are good now!
