### ISSUE TITLE
Default pidfile/lockfile location is on tmpfs

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#150]
**Describe the bug**
When sagan starts, it tries to write to `/var/run/sagan/sagan.pid`

However, on Ubuntu 18.04, `/var/run` is a symlink to `/run` which is on tmpfs.  This means that although you created `/var/run/sagan`, it vanishes when you reboot the system.  Then sagan will not start as it fails to write its pidfile.

**To Reproduce**

After system reboot:

```
# sagan
...
[E] [lockfile.c, line 119] Cannot create lock file (/var/run/sagan/sagan.pid - No such file or directory)
```

The location is configurable in sagan.yaml as `vars.sagan-groups.LOCKFILE`.

**Expected behavior**
After system reboot, I expected sagan to restart successfully.

**Possible solutions**
The primary purpose is not as a pidfile (which is not needed when directly supervised, e.g. under systemd), but as a lockfile to prevent multiple instances of sagan reading the same fifo.

Therefore I suggest:

1. Since the default configuration already uses `/var/sagan/fifo/sagan.fifo`, make the default lockfile location `/var/sagan/sagan.pid` which is on persistent storage. OR:
2. Get rid of the pidfile entirely, and take an `flock(2)` or `fcntl(2)` exclusive lock on the fifo itself.  I think this is a better solution: it is simpler, and has fewer race problems.  (It may not work if the fifo node is stored on an NFS server, but that would be a really weird configuration)

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by beave** [comment]
The lock file is to prevent multiple Sagan "readers" on the same FIFO.  While you can have multiple "writers" to a named pipe,  multiple readers cause an issues.     I know how advisory locks work with fcntl/flock write locks work ((we used those with shared memory objects) ) but I'm not sure how well advisory locks will work with read (ie - out side Sagan.. which all bets are off anyways).

The lock file also serves other purposes.  For example,  logrotate can use the lock file to restart certain Sagan instances.   We have scripts that run after a rule update that use the pid/lock file to send a HUP to reload rules (I don't want to reload _all_ Sagans).

**Comment by candlerb** [comment]
> While you can have multiple "writers" to a named pipe, multiple readers cause an issues.

Multiple writers isn't great either; the messages may be interspersed not on line boundaries, hence corrupted.  If you needed to support multiple writers then Unix domain sockets would be the way to go.

> but I'm not sure how well advisory locks will work with read (ie - out side Sagan.. which all bets are off anyways).

Indeed, only Sagan will honour the locking mechanism - it doesn't matter whether that mechanism is using the pidfile, or taking an exclusive lock on the fifo, or anything else.

But that's simple to deal with: to prevent other processes reading the fifo, use permissions.  e.g. make the fifo mode 420, owner sagan, group syslog.  Then only sagan can read and syslog can write.

**Comment by candlerb** [comment]
So really the only issue is that `/var/run/sagan/sagan.pid` may be a suitable location on FreeBSD, but is not a suitable location on a modern Linux that uses tmpfs.  Should it just be changed to `/var/sagan/sagan.pid` ?

Alternatively it could just use `/var/run/sagan.pid`, which would have to be done before dropping privs.

**Comment by beave** [comment]
Yes. I would agree with the change of location.      This is also an issue on Debian (which makes sense).

**Comment by beave** [comment]
Okay.  I decided to handle this similar to how other programs deal with lockfiles  (mysql, etc). When Sagan starts up as "root",  it will stat() the lockfile path/directory.  If it does _not_ exists,  it will be created and ownership given to the "sagan" users.  It will also create the lockfile and give ownership to Sagan.  

 At that point,  Sagan will "drop privs". 

This allows Sagan to remove the lockfile without "root" privs.  I think this will work out much better.

**Comment by beave** [comment]
Needs testing... I'll leave open for now.

**Comment by beave** [comment]
I believe this was resovled in issue #150.   Please let me know if there are other problems.  Thank you.
