### ISSUE TITLE
Spurious detection of nested JSON

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#151]
**Describe the bug**
I keep seeing the following:

```
[W] [input-json.c, line 364] Detected JSON nest but Libfastjson errors. The log line was: ""
```

I am writing JSON to the fifo with a single newline after the closing brace - which is standard practice, formalised as [JSON Lines](http://jsonlines.org/).

(Sagan requires the newline after JSON: if I send multiple JSON objects *without* newline in between, then they are treated as a single log line)

**To Reproduce**
Configure sagan with JSON input and run it in the foreground.

Submit JSON with trailing newline, e.g.

```
echo '{"fromhost-ip":"192.0.2.1","programname":"sshd","timereported":"2001-01-01T00:00:00","msg":" Accepted publickey for ubuntu from 1.2.3.4 port 64868 ssh2: RSA SHA256:"}' >/var/sagan/fifo/sagan.fifo
```

Observe:

```
[W] [input-json.c, line 364] Detected JSON nest but Libfastjson errors. The log line was: ""
[W] [input-json.c, line 364] Detected JSON nest but Libfastjson errors. The log line was: ""
```

**Expected behavior**
JSON-Lines to be accepted without complaint.

**Screenshots**
See above

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

In `SyslogInput_JSON`, I see that `json_str_count` is initialized to 1.  This means that the loop looking for nested JSON always runs over at least one string:

```
    for ( a = 0; a < json_str_count; a++ )
```

Seems it should initialize to 0, and only increment to 1 when reading nested content.

**Comment by beave** [comment]
You are digging in!   Nicely done!

This is extremely new code and hasn't been fully tested or documented! 

The "json_str_count" is initialized to "1" because it an array of all JSON....  "0" becomes the original JSON string, 1 and > become any nests.   

I'm at Suricon right now,   Let me look more into this a bit later.  Thank you!
