### ISSUE TITLE
Trim trailing space?

### ISSUE THREAD

**Issue by candlerb** [beave/sagan#153]
**Is your feature request related to a problem? Please describe.**
Some generated syslog messages have trailing spaces.  Some devices send messages with trailing newline, or even NUL characters (looking at you, Netgear).

liblognorm rules must match the line completely, so there are a some rules in the current rulebase which have a trailing space:

```
$ grep ' $' normalization.rulebase | wc -l
      29
```

Actually some of those are comments (where trailing whitespace is *not* significant).  So the real rules with trailing whitespare are:

```
$ grep '^[^#].* $' normalization.rulebase | wc -l
       7
```

This trailing whitespace is invisible in the editor, and hence these rules are fragile and likely to be broken by accident.  Some have comment warnings saying so.

Two of the rules end with `%-:rest%` followed by a space:

```
$ grep ':rest% $' normalization.rulebase | sed 's/ $/%20/'
rule=: time=%-:word% devname=%-:word% devid=%-:word% logid=%-:word% type=%-:word% subtype=%-:word% level=%-:word% vd=%-:word% srcip=%src-ip:@ipaddr% srcport=%src-port:number% srcintf=%-:word% dstip=%dst-ip:@ipaddr% dstport=%dst-port:number% dstintf=%-:word% %-:rest%%20
rule=: %username:char-to:\x3a%: %-:number% incorrect password attempts %-:rest%%20
```

This is confusing: it *does* actually work, but only because everything after %rest% is [ignored](https://www.liblognorm.com/files/manual/configuration.html#rest).

(There is one rule which ends with `%therest:rest%,` and the trailing comma serves no purpose)

**Describe the solution you'd like**
I cannot think of any case where leading or trailing whitespace is *significant* - that is, your decision as to whether to alert or not would depend on the presence of that whitespace.

Therefore, I think it would make sense to trim all leading and trailing whitespace (including control characters) from every message, before processing it.  As a side effect this also fixes problem #148.

**Describe alternatives you've considered**
If the current behaviour is to be retained, then at very least I would suggest changing the trailing whitespace in existing rules to ~~`%20`~~ `\x20`:

```
sed '/rule=/s/ $/\\x20/' normalization.rulebase
```

**Additional context**
N/A

**Comment by beave** [comment]
Also.. the space is added as part the syslog-ng/rsyslog template.

**Comment by candlerb** [comment]
> Also.. the space is added as part the syslog-ng/rsyslog template.

That's not entirely correct.  Using the *pipe* input for syslog-ng, the space is added as part of the template; but using the *json* input a leading space is added in [C code](https://github.com/beave/sagan/blob/master/src/input-json.c#L175), and it's hard-coded.  I've made a PR #149 to address this.

Anyway, that issue around leading space and JSON is dealt with separately in #148.

What I was trying to raise in this issue is the fragility of liblognorm rules with trailing spaces; I will rename this issue to say "trailing space" only.

The issue is:

* liblognorm rules must match exactly.  If the received syslog message has a trailing space, the liblognorm rule also needs a trailing space.  There are some examples of this in the existing rulebase.
* When editing normalization.rulebase, it's easy to overlook these invisible end-of-line spaces, or accidentally add/remove them.  There is no test suite for them AFAICS.
* Some of the existing lines in normalization.rulebase have trailing spaces where they are not needed, causing additional confusion (e.g. space after `%-rest%`, space after comment)

I was proposing either:

* Trim trailing space from both the inbound message and the rules; or
* Replace trailing space in rules with `%20` to make them explicit where required, and remove them where not required

**Comment by beave** [comment]
I like the %20 within the rulebase itself.  I've run into this personally and you are correct, it can be frustrating and confusing.

**Comment by beave** [comment]
Thanks.  I'm going to close this one.
