### ISSUE TITLE
journald/journalctl integration

### ISSUE THREAD

**Issue by FedericoCeratto** [beave/sagan#155]
Hello and thank you for developing Sagan.

Is it possible to feed Sagan from journald?

Native support could be better, but perhaps integration using JSON on a fifo is possible.

**Comment by beave** [comment]
I'm not sure.  I know that rsyslog has native journald support.   You might be able to use that to feed Sagan.

**Comment by FedericoCeratto** [comment]
`sudo journalctl -f -o json` generates a stream of JSON documents with all the available key/value pairs including e.g. the function, source code file and line that generate a log. Perhaps it can be fed directly into the named FIFO in https://sagan.readthedocs.io/en/latest/sagan-json.html#json-via-named-pipe-fifo ?

**Comment by beave** [comment]
Yes! That should actually work.   Good idea.  You'll have to create a input-map for it but that should work.

**Comment by beave** [comment]
I'm going to go ahead and close this.   I've added the following documentation: 

https://sagan.readthedocs.io/en/latest/journald.html

We also create the following "journald" mappings: 

https://github.com/beave/sagan-rules/blob/master/json-input.map#L53-L61

Thank you.  I'll add you to the Sagan "credits" (see credits.c) ASAP.
