### ISSUE TITLE
A couple of input-json issues

### ISSUE THREAD

**Issue by rfoster55** [beave/sagan#156]
Hi,

I'm reporting a couple of problems encountered while doing testing of the JSON processing.  These both pertain to input-json.c.

- Some Windows Events contain GUID fields that begin with "{" causing SyslogInput_JSON() to check for nested JSON-- which it is not.  The field is then omitted.  If line 118 looked like this:
`            if ( val_str != NULL && val_str[0] == '{' && (json_obj2 = json_tokener_parse(val_str)))`
The event will fall through to the non-nested JSON code and be included while retaining the speed benefit described in the comment.

- Also, we will occasionally encounter Windows Events with more than 50 JSON fields.  The definition of _Sagan_Proc_Syslog currently looks like this:
`    char json_key[50][64]; 
    char json_value[50][1024];  
`
A larger array size would help but there is no check for the array size in SyslogInput_JSON() and a seg fault can occur.  Something like this at line 100 prevents overrunning the array:
`    int iSize_jsonArrays = sizeof(SaganProcSyslog_LOCAL->json_key) / sizeof(SaganProcSyslog_LOCAL->json_key[0]);

    /* Search through all key/values looking for embedded JSON */
    while (!json_object_iter_equal(&it, &itEnd) && (SaganProcSyslog_LOCAL->json_count < iSize_jsonArrays))
`

Let me know if you'd like me to do a pull request.

**Comment by beave** [comment]
We ran into similar issues.   We've bumped up the json_key size to 256 and is now configurable via the sagan-def.h..   Please checkout the latest code base and see if it resolves your issue.   Would it be possible to get an example log with the GUID.    If you have a work around for that issue,  i'd love to see your code (via pull).  If not,  example data would greatly help.  Thank you

**Comment by beave** [comment]
Pretty sure this has been resolved.  If not,  please open a new issue.
