### ISSUE TITLE
Inconsistent max syslog_tag length settings and tmpbuf length

### ISSUE THREAD

**Issue by smr1983** [beave/sagan#157]
In sagan-defs.h the MAX_SYSLOG_TAG length is 50 chars, in rules.h the s_tag length is 10 chars, therefore matching rules with syslog tags longer than 10 chars isn't working as expected.

At the same time s_program has a max length of 256 and tmpbuf has a max length of 128, therefore the s_program length can exceed tmpbuf in engine.c.

**To Reproduce**
1. Create a rule with syslog_tag longer than 10 chars
2. When debugging engine.c only part of the configured syslog_tag is present in s_tag on line 470.

**Expected behavior**

- An error when loading rules which exceed the max length for both the complete syslog_tag and individual pipe seperated tags.
- A total length of at least the same length as programname (256)

**Additional context**
Related google group topic: https://groups.google.com/forum/#!topic/sagan-users/96Iz8hoc9l4

I'm creating a pull request with:
- A max_syslog_tag_size specification in sagan-defs.h for the size in the rule file with a size of 256
- Using that max_size for the size of s_tag in rules.h
- A larger tmpbuf size (256 instead of 128) in engine.c
- Raising errors when the total string length in the rule exceeds the max_syslog_tag_size and for individual items the max length of max_syslog_tag (This could be extended to other items such as programname)

**Comment by beave** [comment]
Thanks.. let me look this over.

**Comment by beave** [comment]
Looks great.  Merged.
