### ISSUE TITLE
[Question] Configure Sagan

### ISSUE THREAD

**Issue by UET-HDCien** [beave/sagan#159]
Hello everyone,
I want to add  ".c" and ".h" file in "src" folder to expand some Sagan feature, I add some line in Makefile in ```src``` folder to build it but each time I run ```./Configure```, my Makefile will be reset and I need to add from begin. How can I do to make Makefile include lines to build my file each time run  ```./Configure```. Thank you so much.

**Comment by beave** [comment]
You don't add directly to the Makefile.  These are generated by autoconf/automake/etc.    You would add them to the src/Makefile.am and re-run the autogen.sh script.   It would likely be a good idea to read up about how the autoconf/automake/etc work as well.   I'm going to close this,  let me know if you have any other issues.
