### ISSUE TITLE
Scope flexbits to usernames

### ISSUE THREAD

**Issue by smr1983** [beave/sagan#163]
The option to scope flexbits to usernames, so that you can differentiate flexbits on the username in the logs.

Expand flexbits with the "username" option, so the options become:
flexbits: {unset|isset|isnotset},{by_src|by_dst|both|reverse|none|username},{flexbit name}

This issue will be mentioned in a pull request, I'm happy to receive feedback for an alternative solution.

**Comment by beave** [comment]
Thank you!  Let me look into this.

**Comment by beave** [comment]
Merged.
