### ISSUE TITLE
Compilation failure in src/config-yaml.c

### ISSUE THREAD

**Issue by danachee** [beave/sagan#165]
**Describe the bug**
In lines 676 and 692, there is a missing ) so that the compile fails:

 if (!strcasecmp(value, "enabled" && !strcasecmp(value, "true" ) )

[should be a ) after "enabled"]

**To Reproduce**

Compile with libfastjson disabled (having trouble with configuration "liking" the CentOS 8 install of it)

**Expected behavior**
Compilation should not fail

**Screenshots**
config-yaml.c:676:78: warning: passing argument 2 of 'strcasecmp' makes pointer from integer without a cast [-Wint-conversion]
                                             if (!strcasecmp(value, "enabled" && !strcasecmp(value, "true" ) )
                                                                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Desktop (please complete the following information):**
 - OS: CentOS 8

**Comment by beave** [comment]
This should be corrected.  Let me know if it is not.
