### ISSUE TITLE
dst-port / src-port wrong if liblognorm fails

### ISSUE THREAD

**Issue by h8h** [beave/sagan#44]
Hey

I'm writing my own normalization rules for the iptables ruleset which is compiled via the [Firewall Builder](http://www.fwbuilder.org/).

With these rulebases some messages get normalized and some not. For those which can't be normalize by sagan / Liblognorm the source and dest port is wrong. It's exactly the same as the previous message which was successfully normalized.
```
[D] Liblognorm DEBUG output:
[D] ---------------------------------------------------
[D] Log message to normalize: [xxx.xxxxx] RULE x -- DENY IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=192.168.0.11 DST=192.168.0.1 LEN=xx TOS=0x00 PREC=0x00 TTL=xx ID=xxxx PROTO=UDP SPT=80 DPT=80 LEN=xx
[D] Parsed: { "dst-port": "80", "src-port": "80", "proto": "UDP", "dst-ip": "192.168.0.1", "src-ip": "192.168.0.11" }
[D] Source IP: 192.168.0.11
[D] Destination IP: 192.168.0.1
[D] Source Port: 80
[D] Destination Port: 80
[D] Source Host:
[D] Destination Host:
[D]
[D] Liblognorm DEBUG output:
[D] ---------------------------------------------------
[D] Log message to normalize: [xxxx.xxxx] RULE x -- DENY IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=0.0.0.0 DST=224.0.0.1 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2
[D] Parsed: { "originalmsg": "[xxxx.xxxx] RULE x -- DENY IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=0.0.0.0 DST=224.0.0.1 LEN=32 TOS=0x00 PREC=0xC0 TTL=1 ID=0 DF PROTO=2 ", "unparsed-data": "DF PROTO=2 " }
[D] Source IP: 0
[D] Destination IP: 0
[D] Source Port: 80
[D] Destination Port: 80
[D] Source Host:
[D] Destination Host:
[D]
```
Maybe it has something in common with the line [194](https://github.com/beave/sagan/blob/master/src/sagan-liblognorm.c#L194) / [197](https://github.com/beave/sagan/blob/master/src/sagan-liblognorm.c#L197) . If `tmp` is `NULL` `SaganNormalizeLiblognorm->src_port` will never be write, but later read. In this case it should be reset like the ip_src, ip_dst, src_host in line [109](https://github.com/beave/sagan/blob/master/src/sagan-liblognorm.c#L109).

I don't want to offer a PR, because I don't know if this is the cause.

Cheers

**Comment by beave** [comment]
Can you send a copy of the rule and the rulebase ?  I'll look at it later tonight .  Thanks !

--

Champ Clark III
cclark@quadrantsec.com

----- Reply message -----

**Comment by h8h** [comment]
I'm out of office right now. Tomorrow I can sent you the rule(base)s.

Sorry perhaps I was not clear enough.

This issue is not about liblognorm isn't working well, it's about what happen if some input gets normalize and the following input does not. In this case the previous port is not reset (by sagan) to the default or zero value, it gets the port from the last (successfull) normalization.

**Comment by beave** [comment]
I'm out today as well.  I think I understand. I just wanted the rule/rulebase so it might be easier to replicate.  

Ports can also be defined in the rule set and the sagan_port option.  I dont think that is what is happening here.  

I'll look at it asap/tonight.

--

Champ Clark III
cclark@quadrantsec.com

----- Reply message -----

**Comment by beave** [comment]
Ok.  I believe it's fixed.  Can you test and make sure?  Thank you for the bug submission!

**Comment by h8h** [comment]
I'll do that ASAP. Thanks!

**Comment by h8h** [comment]
If the message / input can't be parsed the dst / src ports are set to zero. So everything works fine now and works as expected. Thanks for that quick fast fix!!
