### ISSUE TITLE
Support active-response per rule

### ISSUE THREAD

**Issue by jonschipp** [beave/sagan#50]
It would be useful if you could set an active-response script per rule similar to `email: bob@example.org`.
This way we don't have to fork the script for every alert thus saving cycles and also don't have to write scripts to test SID or similar before performing SID related action. It would also be nice if sagan supported more than one active-response script. Supporting `active-response: /path/to/script` in the rule body would be dope. That way I can have multiple concise scripts like:
```
alert tcp ... active-response: /path/sagan/blacklist.sh ...
alert syslog ... active-response: /path/sagan/intel.sh ...
```

**Comment by beave** [comment]
This wouldn't be hard to do.  I believe I could tie to to src/processors/sagan-external.c pretty easy to the rule (*cough* famous last words *cough*).   Could we perhaps come up with something other than "active-response"?    

The reason;  that makes me think of an "OSSEC" term(s).  Is there an "inactive response"? :)  Is there any time it wouldn't be "active".  Maybe just "response"?  Maybe just "execute"?  Hmmmm.

I do think your use case is complete valid and worth doing.   On a side note,  if I where to want to "actively" block IP addresses,  I'd want to use the Snortsam plugin.   It's a much cleaner solution IMHO. 

However,  your example is a good one.    Let me know your thoughts.

**Comment by beave** [comment]
I meant src/output-plugins/sagan-external.c

**Comment by jonschipp** [comment]
ah, my days with OSSEC are starting to show :) 
How about command, execute, run, execute, script, or launch in that order of preference?

We don't use snortsam - we have our own Black Hole Router software that has an HTTP based API.

**Comment by beave** [comment]
I started to call it "external",  since the output processor is named that as well.   

We wrote a output plugin for MySQL with Snortsam.   We have a client that uses a MySQL database to there BGP cloud,  and they use that to block attacks.  So,  Sagan see's the attack -> contacts Snortsam -> Snortsam INSERT's into the database :)

Snortsam does some cool stuff. 

Anyways!  I'll have this done probably later tonight.  I just have to add the rule option :)

**Comment by jonschipp** [comment]
Awesome, thanks man!

**Comment by beave** [comment]
Okay..  I've added the "external: /tmp/myprogram;" style option to Sagan rules.  Please test and let me know what you think.  It's super duper alpha :)  I havent tested very much at all.

It works exactly like the "external" processor works.  That is,  it hands the data from Sagan to your program via stdin.  

Let me know how it works for you and thanks!

**Comment by beave** [comment]
Added in some error checking in both the "external" processor and "external" rule option (ie - is the target file there?  is it executable?).   I also removed the "external" option for "parseable" and "alert".  It's only "parseable"  now.  Basically,  Sagan will hand to your program via STDIN the following:

ID:{generator_id}:{signature_id}
Message:{signature message}
Classification:{signature_classtype}
Drop:{True/False}
Priority:{signature_priority}
Date:{trigger_date}
Time:{trigger_time}
Source:{source_ip}
Source Port:{source_port}
Destination:{destination_ip}
Destination Port:{destination_port}
Facility:{syslog_facility}
Syslog Priority:{syslog_priority}
{syslog_message_here}

Let me know if there is any other data you'd like passed.

**Comment by beave** [comment]
Hey Jon, 

I did some testing on the external processor,  and the rule option "external".    Both seemed to function as expected.   Please do some testing on your side and let me know if you run into any problems.   I'm going to go ahead and close this.   I'll re-open if you run into any issues.

On a side note:  The "--debug external" works with both the external processor and rule option.  

Thanks again!

**Comment by jonschipp** [comment]
Hey Champ, having a little issue. After updating to sagan upstream my global external script specified in sagan.conf no longer works.

```
[*] -------------------------------------------------------------------------------
[*]
[*] Attempting to open syslog FIFO (/var/run/sagan.fifo).
[*] Successfully opened FIFO (/var/run/sagan.fifo).
[W] [output-plugins/sagan-external.c, line 67] In sagan_ext_thread()
[D] [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/active-response.sh
[W] [output-plugins/sagan-external.c, line 67] In sagan_ext_thread()
[D] [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/active-response.sh
```
I tried running switching to running sagan as root in case it was permission based but doesn't seem to be. I can manually run the script with the parsable input and it works.
`echo -e "\nID:1:10000030\nMessage:[TEST] TEST\nClassification:suspicious-command\nDrop:False\nPriority:1\nDate:2015-07-31\nTime:14:59:23\nSource:141.142.148.97\nSource Port:514\nDestination:141.142.148.97\nDestination Port:514\nFacility:user\nSyslog Priority:notice\nSyslog message: TEST TEST\n" > parseable.txt`
`sudo -u sagan cat parseable.txt | ./active-response.sh` works - send alert to our chat channel

Here's a system call trace if that helps.
```
[pid 29058] read(7,  <unfinished ...>
[pid 29841] <... futex resumed> )       = 0
[pid 29840] <... write resumed> )       = 93
[pid 29839] <... futex resumed> )       = 0
[pid 29839] futex(0x62ff84, FUTEX_WAIT_PRIVATE, 1842, NULL <unfinished ...>
[pid 29840] write(1, "[W] [output-plugins/sagan-external.c, line 67] In sagan_ext_thread()\n", 69) = 69
[pid 29840] pipe([8, 9])                = 0
[pid 29840] pipe( <unfinished ...>
[pid 29841] futex(0x62ff84, FUTEX_WAIT_PRIVATE, 1843, NULL <unfinished ...>
[pid 29840] <... pipe resumed> [10, 11]) = 0
[pid 29840] clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fbf30ac49d0) = -1 ENOMEM (Cannot allocate memory)
[pid 29840] close(8)                    = 0
[pid 29840] close(11)                   = 0
[pid 29840] write(9, "\nID:1:10000030\nMessage:[TEST] TEST\nClassification:suspicious-command\nDrop:False\nPriority:1\nDate:2015-07-31\nTime:14:59:23\nSource:141.142.148.97\nSource Port:514\nDestination:141.142.148.97\nDestination Port:514\nFacility:user\nSyslog Priority:notice\nSyslog message: TEST TEST\n", 270) = -1 EPIPE (Broken pipe)
[pid 29840] close(9)                    = 0
[pid 29840] read(10, "", 10240)         = 0
[pid 29840] close(10)                   = 0
[pid 29840] wait4(-1, NULL, 0, NULL)    = -1 ECHILD (No child processes)
[pid 29840] stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3543, ...}) = 0
[pid 29840] write(3, "[D] [07/31/2015 14:59:23] - [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/active-response.sh\n", 115) = 115
[pid 29840] write(1, "[D] [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/active-response.sh\n", 91) = 91
[pid 29840] futex(0x62ff84, FUTEX_WAIT_PRIVATE, 1844, NULL^C <unfinished ...>
```

**Comment by beave** [comment]
Can you make the script dump the input of what it has received to a file?  That code hasn't been touched since we last messed with it.  

I have a Perl routine that you can replace and it simply records what Sagan has sent the routine.  

Let me know your thoughts. 

--

Champ Clark III
cclark@quadrantsec.com

----- Reply message -----

**Comment by jonschipp** [comment]
The script dumps to file as well so I can review the parseable info. Since external hasn't been working nothing is written to the file. I would expect to see a execve() or something but that's not in the source. I don't think the script is getting executed.

**Comment by beave** [comment]
I'll look asap.   I'm on vacation right now.  It calls execl() if you look at the code.   Let me know what your script output says and I'll also run some tests.   

--

Champ Clark III
cclark@quadrantsec.com

----- Reply message -----

**Comment by jonschipp** [comment]
No hurry, enjoy your vacation

**Comment by beave** [comment]
I tested and can't replicate.   Do you want me to send you my routine for testing ?

--

Champ Clark III
cclark@quadrantsec.com

----- Reply message -----

**Comment by jonschipp** [comment]
That will be fine, thanks

On Tue, Aug 4, 2015 at 5:26 PM, Champ Clark <notifications@github.com>
wrote:

>
> I tested and can't replicate. Do you want me to send you my routine for
> testing ?
>
> --
>
> Champ Clark III
> cclark@quadrantsec.com
>
> ----- Reply message -----
> From: "Jon Schipp" <notifications@github.com>
> To: "beave/sagan" <sagan@noreply.github.com>
> Cc: "Champ Clark" <cclark@quadrantsec.com>
> Subject: [sagan] Support active-response per rule (#50)
> Date: Sat, Aug 1, 2015 01:12
>
>
> No hurry, enjoy your vacation
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/beave/sagan/issues/50#issuecomment-126865821
>
> I tested and can't replicate. Do you want me to send you my routine for
> testing ?
>
> --
>
> Champ Clark III
> cclark@quadrantsec.com
>
> ----- Reply message -----
> From: "Jon Schipp" <notifications@github.com>
> To: "beave/sagan" <sagan@noreply.github.com>
> Cc: "Champ Clark" <cclark@quadrantsec.com>
> Subject: [sagan] Support active-response per rule (#50)
> Date: Sat, Aug 1, 2015 01:12
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beave/sagan/issues/50#issuecomment-127779448>.
>



-- 
Jon Schipp,
jonschipp.com, sickbits.net,  <http://goog_1056813495>open-nsm.net,

**Comment by beave** [comment]
Jon, 

My "test" routine is at: 

https://github.com/beave/sagan/tree/master/extra/external-test 

It's a pretty simple perl routine. Let me know how it works for you.

**Comment by jonschipp** [comment]
`/usr/local/sbin/sagan --debug external --user sagan --config /usr/local/etc/sagan.conf` 

```
$ grep external sagan.conf 
output external: /usr/local/etc/external-test
```

```
ls -l external-test 
-rwxr-xr-x 1 sagan sagan 666 Aug  7 13:30 external-test
```

```
[*]            Dropped                  : 0 (0.000%)
[*] -------------------------------------------------------------------------------
[W] [output-plugins/sagan-external.c, line 67] In sagan_ext_thread()
[D] [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/external-test
```

But nothing is there
```
 ls -l /tmp/
total 16
drwx------. 2 root root 16384 Feb 26 14:23 lost+found
```

**Comment by jonschipp** [comment]
Okay, I'm trying to debug this and if I understand this all correctly execl() is not getting called.

> The exec family of functions replaces the current process image with a new process image.  The functions described in this manual page are front-ends for the function execve(2).

Okay so if the function called is `execl()` - I would expect to see a `execve(2)` when using a system call tracer because `execl()` is a front-end for `execve(2)` but I don't see it.

```
$ strace -e execve -f -p 4465
Process 4465 attached with 1004 threads - interrupt to quit
[empty]
```

Now trying a function tracer, I don't think execl() is getting called at all.

```
$ ltrace -e execl -f -p 4465
[empty]
```

Debug output again:
```
[W] [output-plugins/sagan-external.c, line 67] In sagan_ext_thread()
[D] [output-plugins/sagan-external.c, line 171] Executed /usr/local/etc/external-test
```

**Comment by jonschipp** [comment]
I rebooted the box and it works now.. strange

**Comment by beave** [comment]
WTF...
