### ISSUE TITLE
Host modifier for matching hostname or ip

### ISSUE THREAD

**Issue by jonschipp** [beave/sagan#51]
It would be really useful to be able to match syslog message originating hosts (by IP or hostnames) for which certain SID/rules should apply. I'm thinking specifically about being able to profile my hosts with custom sagan rules based on their configurations. Maybe a host modifier like
 `... program ssh; host: %BRO_SERVERS%` where the rule only matches if a host in %HOSTS% has generated the syslog message currently being analyzed. Then we could do that like create lists of hosts to match using variables. 
```
BRO_SERVERS [ nids1, nids2 ... ]
WEB_SERVERS [ web1, web2 ... ]
```
OSSEC is able to match the hostname using `<hostname></hostname>` and it would be great if Sagan could support this as well. Thanks

**Comment by beave** [comment]
That was the idea behind $HOME_NET and $EXTERNAL_NET ( in the rule ).  This way,  you can use network block / CIDR information to apply to rules.   However,   we've rarely needed it at Quadrant.   That code has not been completed (yet).   

It's on the white board :)

**Comment by jonschipp** [comment]
That would be great, glad to hear that it's planned.

**Comment by beave** [comment]
Adam Hall added support for $HOME_NET and $EXTERNAL_NET.  You might want to test this.   I should point out,  this works with the normalized data.

**Comment by jonschipp** [comment]
W00t, thanks
