### ISSUE TITLE
Originating host in alert

### ISSUE THREAD

**Issue by jonschipp** [beave/sagan#52]
It is possible to add the host field of a syslog message to an alert? 
My problem is that all my alerts show (see below) `10.1.2.3:514 -> 10.1.2.3:514` to identify the host but that is the IP address of our redundant CARP address for syslog forwarding redundancy which hosts from our network forward to so looking at this alert I'm not able to tell from which host this message originated from. Maybe it could be added after the time stamp or before the facility? I don't know if this will break anything relying on the alert format. What do you think?

[Infrastructure image](https://sickbits.net/wordpress/wp-content/uploads/2013/12/syslog_rearchitecture.png)

To find the host from which this syslog message was received I grep through our log archive to find a match which, given by the common messaged exhibited here, will return hundreds-thousands of results. Matching by timestamp will help but creating regexs all the time is a pain just to verify something.
```
[**] [1:5000119] [SYSLOG] Authentication failure - Brute force [**]
[Classification: unsuccessful-user] [Priority: 1]
2015-06-07 03:32:10 10.1.2.3:514 -> 10.1.2.3:514 daemon notice
Message:  Exiting: authentication failed
[Xref => http://wiki.quadrantsec.com/bin/view/Main/5000119]
```

**Comment by beave** [comment]
This isn't a problem for the alert "file".   I'd also like to add the protocol as well.  

It becomes a problem when adding it to unified2.   Right after Sagan 1.0,   we're going to start using the unified2 ExtraData headers to store information like this.   This probably a few weeks off. 

I'll make the change to the alert file output ASAP.   I'll likely add it after the priority (?)

**Comment by jonschipp** [comment]
That sounds great, thanks!

**Comment by beave** [comment]
Sorry Jon!  I completely forgot about this.  Its been added to the alert file. 

unified2 extra data will come in Sagan 1.0+

**Comment by jonschipp** [comment]
Thanks!

On Fri, Jun 19, 2015 at 3:21 PM, Champ Clark <notifications@github.com>
wrote:

> Closed #52 <https://github.com/beave/sagan/issues/52>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beave/sagan/issues/52#event-335597125>.
>



-- 
Jon Schipp,
jonschipp.com, sickbits.net,  <http://goog_1056813495>open-nsm.net,

**Comment by jonschipp** [comment]
Champ, regarding this I see an IP address not a hostname. The IP in this case is that of our rsyslog forwarder so we have no way of determining which system the log came from - this happens for every log. Can the hostname pulled and place d in the new field after priority? or maybe an option in sagan.conf to choose whether the IP or hostname should be there
```
[**] [1:10000020] [TEST] route update  [**]
[Classification: successful-user] [Priority: 1] [1.1.1.95]
2015-07-16 10:51:17 1.1.1..95:514 -> 1.1.1.1.95:514 user notice
Message:  Thu, 16 Jul 2015 10:51:15 | INFO     | 2142   | reactor       | Updated peers dynamic routes successfully
```

**Comment by beave** [comment]
What would be better would be to have rsyslog UDP "spoof" the traffic.   That way,  the original message stays in tact.  See:

http://www.rsyslog.com/doc/v8-stable/configuration/modules/omudpspoof.html

The IP address is used for a lot of different things.  However,  I do plan on adding the syslog supplied hostname to the FIFO format.   However,  I need to get the current code stable/released first.

If you do the rsyslog spoofing,  you'll get the effect you want.

**Comment by jonschipp** [comment]
Yeah, I would have done that but we use TCP as the transport and RELP above that when we can to avoid loss of messages.

**Comment by beave** [comment]
You can still use TCP with RELP.  Just spoof the packets to Sagan,  leave your clients connections alone. 

You could also run Sagan on the same server that rsyslog is on.  That's what we do in most cases.  That way,  you get the best of all worlds.  

Just a thought.

**Comment by jonschipp** [comment]
It's not ideal but omudpspoof will do the trick. Thanks for the suggestions.

**Comment by beave** [comment]
After I get RC5 released,   I'll be modifying the Sagan FIFO to support the syslog hostnames.  We can then add in support for the "from:" fields and some other stuff.   If I can manage to not keep adding things for a week or two (just bug fixes),  then I'll release and we can move forward :)

**Comment by jonschipp** [comment]
dope - can't wait

On Tue, Jul 21, 2015 at 1:35 PM, Champ Clark <notifications@github.com>
wrote:

> After I get RC5 released, I'll be modifying the Sagan FIFO to support the
> syslog hostnames. We can then add in support for the "from:" fields and
> some other stuff. If I can manage to not keep adding things for a week or
> two (just bug fixes), then I'll release and we can move forward :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beave/sagan/issues/52#issuecomment-123430818>.
>



-- 
Jon Schipp,
jonschipp.com, sickbits.net,  <http://goog_1056813495>open-nsm.net,
