### ISSUE TITLE
support for embedded variables

### ISSUE THREAD

**Issue by jonschipp** [beave/sagan#55]
It would be nice if support could be added for embedded variables, and probably the result of the variable features in snort e.g. negation, modifiers, etc. I haven't seen most of the stuff documented so I'm finding out by trial and error. It's not clear to me how much of the snort config is supported.
```
var CAT cat
var DOG dog
var ANIMALS [$CAT,$DOG]
```

`alert syslog $EXTERNAL_NET any -> $HOME_NET any    (msg:"[TEST] Var Test Embedded"; meta_content:"animal %sagan%", $ANIMALS; classtype: successful-user; sid:10000090; rev:1;)`
`alert syslog $EXTERNAL_NET any -> $HOME_NET any    (msg:"[TEST] Var Test cat"; meta_content:"animal %sagan%", $CAT; classtype: successful-user; sid:10000091; rev:1;)`
`alert syslog $EXTERNAL_NET any -> $HOME_NET any    (msg:"[TEST] Var Test dog"; meta_content:"animal %sagan%", $DOG; classtype: successful-user; sid:10000092; rev:1;)`

```
$ logger "animal cat"
[**] [1:10000091] [TEST] Var Test cat [**]
[Classification: successful-user] [Priority: 1]
2015-07-15 12:23:51 141.142.148.97:514 -> 141.142.148.97:514 user notice
Message:  animal cat

$ logger "animal dog"
[**] [1:10000092] [TEST] Var Test dog [**]
[Classification: successful-user] [Priority: 1]
2015-07-15 12:23:35 141.142.148.97:514 -> 141.142.148.97:514 user notice
Message:  animal dog
```

**Comment by beave** [comment]
Whoa. Cool idea.  I'll mark this up for a "feature".  Nice.

**Comment by beave** [comment]
This should work now.   I added it to issue #77 bugfix.   Let me know if you run into issues with it.

**Comment by jonschipp** [comment]
Perfect, thanks
