### ISSUE TITLE
bro-intel: domain; matches all logs

### ISSUE THREAD

**Issue by jonschipp** [beave/sagan#56]
Can `bro-intel: domain;` be made to match the INTEL::DOMAIN item anywhere in the log?
The rule below could be really useful.
`alert udp $EXTERNAL_NET any -> $HOME_NET $DNS_PORT (msg: "[BRO] Excessive Bad Domains (1000+)"; bro-intel: domain; after: track by_src, count 1000, seconds 86400; parse_src_ip: 1; parse_dst_ip: 2; classtype: suspicious-traffic; sid: 13000003; rev:1;)`

However, it doesn't work as expected - it seems to match on every log line. Removing the after option further demonstrates this by resulting in
```
kernel: sagan[2330]: segfault at 7facb3e43a60 ip 0000003294247e2c sp 00007fa9f08891e0 error 4 in libc-2.12.so[3294200000+18a000]
init: sagan main process (1378) killed by SEGV signal
```
I don't understand how the domain option currently works for the bro-intel preprocessor. The domain indicator isn't listed in the table at `https://wiki.quadrantsec.com/twiki/bin/view/Main/SaganRuleReference#bro_intel_src_ipaddr_dst_ipaddr`.

**Comment by beave** [comment]
Oh, it's not.  You are correct.  I'll list that ASAP:

I believe there is more info at http://blog.bro.org/2014/01/intelligence-data-and-bro_4980.html

Let me test and see if I can replicate.

**Comment by beave** [comment]
Oh, that looks nice "kernel: sagan[2330]: segfault at 7facb3e43a60 ip 0000003294247e2c sp 00007fa9f08891e0 error 4 in libc-2.12.so[3294200000+18a000]
init: sagan main process (1378) killed by SEGV signal" :(

**Comment by beave** [comment]
looking at it now.

**Comment by jonschipp** [comment]
I wrote that Bro article :) I understand what it does in Bro but it didn't work in Sagan so I suspected it could have been implemented differently.

**Comment by beave** [comment]
Back to the top:

"Can bro-intel: domain; be made to match the INTEL::DOMAIN item anywhere in the log?
The rule below could be really useful."

That's exactly what it does.  It takes anything from your Bro::Intel (from your load file) and looks for matches.   If the any INTEL::DOMAIN hits are found,  they will fire the signature.   I just tested the following rules:

alert syslog $EXTERNAL_NET any -> $HOME_NET any (msg: "[TEST] bro intel domain test"; bro-intel: domain; classtype: suspicious-traffic; sid: 13000007; rev: 1;)

This rule fired as expected.  I think added the after to it: 

alert syslog $EXTERNAL_NET any -> $HOME_NET any (msg: "[TEST] bro intel domain test"; bro-intel: domain; after: track by_src, count 5, seconds 86400; classtype: suspicious-traffic; sid: 13000007; rev:
1;)

I then issues: 

logger " abvruerm.biz "

5 times with no "alerts".  On the 6'th,  it fired as expected. 

There is obviously a problem,  but I havent been able to replicate so far.  I'll keep poking. 

Oh,  I do see the usefulness of the rule!  It's a pretty good idea.

**Comment by beave** [comment]
Hahaha. Nice,  I quote an article you write.  I win. :)

I copied/pasted your rule and altered it to:

after: track by_src, count 5, seconds 86400;

That worked successfully.  Could it be that Sagan isn't parsing your Bro-Intel file correct?

**Comment by jonschipp** [comment]
Just to make sure there wasn't some text in the domain list that matched everything I tried run the indicators from one of the matching log messages, no match as expected:
```
echo "1436982455.390447#011CFCW9a3y0sTbNLzOne#011.1.1.1.1#01141201#0111.1.1.1.2#01188#011AS#011hthta/TERAGRID.ORG#011krbtgt/ORGANIZATION.ORG#011F#011NEEDED_PREAUTH\x00#0111436982254.000000#0111437068654.000000#011-#011T#011F#011-#011-#011-#011-" | grep -f  <(awk '{ print $1 }' domain.intel)
[nothing]
```
I tried keeping one INTEL::DOMAIN entry, used the same rule as you did in last post and it still alerts on all logs. Is it my version of sagan: `[Sagan version 1.0.0-RC5`?

Format looks correct, tab delimited - generated via CIF.
```
hexdump -c domain.intel 
0000000   j   k   d   e   m   l   d   e   l   f   v   u   .   c   o   m
0000010  \t   I   n   t   e   l   :   :   D   O   M   A   I   N  \t   C
0000020   I   F       -       n   e   e   d   -   t   o   -   k   n   o
0000030   w  \t   m   a   l   w   a   r   e       d   o   m   a   i   n
0000040  \t   h   t   t   p   :   /   /   w   w   w   .   s   p   a   m
0000050   h   a   u   s   .   o   r   g   /   q   u   e   r   y   /   d
0000060   b   l   ?   d   o   m   a   i   n   =   j   k   d   e   m   l
0000070   d   e   l   f   v   u   .   c   o   m       (   p   u   b   l
0000080   i   c   )  \t   -  \t   m   e   d   i   u   m  \t   9   5  \n
0000090
```

```
cat domain.intel 
jkdemldelfvu.com        Intel::DOMAIN   CIF - need-to-know      malware domain  http://www.spamhaus.org/query/dbl?domain=jkdemldelfvu.com (public)      -       medium  95
```

sagan.conf:
`processor bro-intel: /usr/local/etc/ip.intel,/usr/local/etc/domain.intel,/usr/local/etc/url.intel`

**Comment by jonschipp** [comment]
It works after compiling from upstream, sorry for wasting your time. I kept holding off on building a new package for it.
