### ISSUE TITLE
new feature - add part of a log line into related alert - syslog output

### ISSUE THREAD

**Issue by work-lako** [beave/sagan#57]
Hello,
I think the following feature could be usefull: 

When a log trigger a sagan alert:
- sagan is able to write the triggered alert and the associated log into an output file
- However, sagan is not able to send the associated log into a syslog message (it only sends the alerts names and alert additional info)

It could be really great if sagan was able to send all the logs wich triggered the alert (raw format) or a part of thoses log, which could be extracted with liblognorm for example (as rsyslog is also able to use the liblognorm lib).

Let me know if you require any further informations on this potential feature.

Regards,

**Comment by beave** [comment]
Hello and thank you for the suggestions. 

1.  Sagan already writes this data to your the  /var/log/sagan/alert file by default.
2.  This might be possible,  but some syslog servers have a limitation on the size of syslog messages.  This means some message might get truncated.    This certainly would not be difficult to do.

In the mean time,  you could write a routine in the language of your choosing and call that via the "external" output plug in. 

I'll leave this ticket open for consideration.  

Thanks again!

**Comment by work-lako** [comment]
Totally agreed however, regarding the "2." 

syslog message limitation can be avoid by :
1 - setting the rsyslog global directive $MaxMessageSize <size_number>  (only with rsyslog, i don't know is something similar exist for syslog-ng). (ref http://www.rsyslog.com/doc/v8-stable/configuration/global/index.html)
2 - setting a higher mtu on the used networks interfaces (ref http://kb.netgear.com/app/answers/detail/a_id/25091/~/guidance-on-the-use-of-jumbo-frames)

So I think the best way to avoid unwanted issues and/or sides effects with networks interfaces configuration could be allowing sagan to add part of the related logs (through the normalize: rule option for example) to the sent syslog message. 

Because usually there is no need to retrieve the entire raw log, only the trigered part is interesting for starting a log investigation

Thanks for yuor quick answers.

**Comment by beave** [comment]
Message size limitation isnt and issue with modern syslog daemon (syslog-ng,  rsyslog).  If Sagan is sending a "large" message to a legacy system,  it might truncate.  However,   this isn't a "Sagan" issue IMHO

So,  would having the standard Sagan syslog alert message with the log message that triggered the event appended to it work?  I don't want to do just liblognorm, because liblognorm is not always used. 

Let me know your thoughts.

**Comment by work-lako** [comment]
You're right the syslog message size are not really a sagan issue.

It OK for me to have the standard Sagan syslog alert message with the log message that triggered the event appended to it. It could be a great beginning !

**Comment by work-lako** [comment]
Hello, 

I have some news on this topic.

1) Read /var/log/sagan/alert through rsyslog imfile module:
As workaround, I tried to use the rsyslog imfie module in order to read the  /var/log/sagan/alert then send the alert and the related log message.

However, I notice an unwanted behavior using this module. It seems that sagan write into /var/log/sagan/alert an empty line and then the alert message followed by the related log message. This sagan behavior prevent rsyslog to send the alert message (with the associated log) until a new alert is generated. See 'http://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html (readmode part).

Rsyslog imfile module (readmode 1) need to find a blank line in order to know where is the end of the message. This behaviour is related to rsyslog imfile module but could be avoid if sagan write the alert message (with the associated log) and then add a blank line after it (the oposite of what sagan currently do). Same problem with the regex read mode.

2) Adding the log message directly into the sagan default syslog output: 
Another solution was to modify the sagan default syslog output in order to contain the related log event. 
Please find below how i did it.
I modified the src/output-plugins/sagan-syslog.c file

Please find below the modified lines :

diff --git a/src/output-plugins/sagan-syslog.c b/src/output-plugins/sagan-syslog.c
index 013a4b1..a2741e5 100644
--- a/src/output-plugins/sagan-syslog.c
+++ b/src/output-plugins/sagan-syslog.c
@@ -54,7 +54,7 @@ void Sagan_Alert_Syslog( _SaganEvent *Event )
 
     /* Template to mimic Snort syslog output */
 
-    char *syslog_template = "[%lu:%s:%s] %s [Classification: %s] [Priority: %d] %s %s:%d -> %s:%d";
+    char *syslog_template = "[%lu:%s:%s] %s [Classification: %s] [Priority: %d] %s %s:%d -> %s:%d - %s";
 
     if ( Event->ip_proto != 1 || Event->ip_proto != 6 || Event->ip_proto != 17 )
         {
@@ -76,7 +76,7 @@ void Sagan_Alert_Syslog( _SaganEvent *Event )
             tmp_proto = "{UDP}";
         }
 
-    snprintf(syslog_message_output, sizeof(syslog_message_output), syslog_template, Event->generatorid, Event->sid, Event->rev, Event->f_msg, Sagan_Classtype_Lookup ( Event->class ), Event->pri, tmp_proto, Event->ip_src, Event->src_port, Event->ip_dst, Event->dst_port);
+    snprintf(syslog_message_output, sizeof(syslog_message_output), syslog_template, Event->generatorid, Event->sid, Event->rev, Event->f_msg, Sagan_Classtype_Lookup ( Event->class ), Event->pri, tmp_proto, Event->ip_src, Event->src_port, Event->ip_dst, Event->dst_port, Event->message);
 
     /* Send syslog message */


And now sagan is able to send alerts with the log message that triggered the event appended to it through it's default syslog output.

Sorry for the long post.


Please let me know your thoughts.

**Comment by beave** [comment]
This looks useful,  but i think I'd like to make it a syslog "option" that can be enabled/disabled.  I'd also like to alert the formating a bit so that it's obviously separated.   Other than that,  looks like an easy enough thing to accomplish. I'm leaving this open to remind me later to patch :)
