### ISSUE TITLE
1.0.1 fails to build on i386

### ISSUE THREAD

**Issue by hpfn** [beave/sagan#64]
Hi,

I put version 1.0.1 on Debian 'sid'. But it fails to build
on *i386. I didn't find any information about it, so I am 
asking here.

It is possible to see the logs here[0]. Please click on
'Build-Attempted'.

[0] - https://buildd.debian.org/status/package.php?p=sagan&suite=unstable

regards,
Herbert

**Comment by hpfn** [comment]
Can I just avoid sse ?

--- sagan-1.0.1.orig/src/Makefile.am
+++ sagan-1.0.1/src/Makefile.am
@@ -34,8 +34,6 @@ parsers/parse-ip.c \
 parsers/parse-port.c \
 parsers/parse-proto.c \
 parsers/sagan-strstr/sagan-strstr-hook.c \
-parsers/sagan-strstr/strstr_sse2.S \
-parsers/sagan-strstr/strstr_sse4_2.S \
 output-plugins/sagan-alert.c \
 output-plugins/sagan-esmtp.c \
 output-plugins/sagan-external.c \

**Comment by hpfn** [comment]
I tried '--enable-system-strstr'.

It builds, but doesn't run:

[E] [sagan-rules.c, line 190] Failed to reallocate memory for rulestruct. Abort!

**Comment by beave** [comment]
What CPU type is this?  Is it a low memory system?  Can you send me your sagan.conf? I'll look into it ASAP.

**Comment by hpfn** [comment]
I don't know about the Debian machine. 

My tests (chroot) is:

$less /proc/cpuinfo
...
model name      : Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
...
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dtherm tpr_shadow vnmi flexpriority ept vpid

$ free
             total       used       free     shared    buffers     cached
Mem:       7992032    7843464     148568     166144     389560    5801192
-/+ buffers/cache:    1652712    6339320
Swap:      8300540          0    8300540

sagan.conf is the default, removed the *bluedot.rules files.

**Comment by hpfn** [comment]
Anyway, the file.

Can't upload the file. I tried. Please see:
http://paste.debian.net/366474/

**Comment by hpfn** [comment]
I tried to upload the file without sucess.

Please see http://paste.debian.net/366474/.

I closed this by mistake

**Comment by beave** [comment]
Whoa.  That's a lot of rules.  Can you try disabling some rules.  I'll be testing shortly ,  but umless you have limited memory,  loading this many rules shouldt be a problem.

**Comment by hpfn** [comment]
It seems you are right!

[*] Out of 1081 rules, 97 Flowbit(s) are in use.
[*] Sagan version 1.0.1 is firing up!
[*] Dropping privileges [UID: 106 GID: 4]
[*] ---------------------------------------------------------------------------
[*] 
[*]  ,-._,-. 	-*> Sagan! <*-
[*]  \/)"(\/	Version 1.0.1
[*]   (_o_)	Champ Clark III & The Quadrant InfoSec Team [quadrantsec.com]
[*]   /   \/)	Copyright (C) 2009-2015 Quadrant Information Security, et al.
[*]  (|| ||) 	Using PCRE version: 8.38 2015-11-23
[*]   oo-oo     Sagan is processing events.....
[*] 
[*] Becoming a daemon!
[*] Spawning 50 Processor Threads.
[*] 

But I still need the '--enable-system-strstr' to compile.

I will wait your reply.
