### ISSUE TITLE
automake warning

### ISSUE THREAD

**Issue by hpfn** [beave/sagan#65]
Hi,

Looking the building process of sagan I have this warning:

Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPF
LAGS')
src/Makefile.am:7: warning: source file 'parsers/parse-ip.c' is in a subdirectory,
src/Makefile.am:7: but option 'subdir-objects' is disabled

automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.

regards,

**Comment by beave** [comment]
Fixed a bunch of these.  Should run much cleaner now.   Thank you for reporting.
