### ISSUE TITLE
liblognorm version recommended

### ISSUE THREAD

**Issue by CyberTaoFlow** [beave/sagan#68]
Which liblognorm release is recommended?  I know there were major changes in 2.x which is the current master branch, should we be building with 1.x stable ? https://github.com/rsyslog/liblognorm/tree/v1-stable

**Comment by beave** [comment]
Sagan is using the latest off of https://github.com/rsyslog/liblognorm (current master).

When compiling Sagan,  you might run into this issue:
https://github.com/rsyslog/liblognorm/issues/204

Sagan now also uses libfastjson,  which liblognorm uses. 

We need to update our compiling "howto" to reflect these and other changes.  We'll get to that ASAP.  Please let me know if you run into any problem.

I'm going to keep this open.  If everything works out,  please close it.  Thank you.

**Comment by CyberTaoFlow** [comment]
I'll build with the current master and test, should have more later

**Comment by CyberTaoFlow** [comment]
I built with the current master of liblognorm and compiled all my .rulebase files into one file using 'cat *.rulebase >> normalize.rulebase'.  Things seemed to be working well so I added the 'version=2' string to the normalize.rulebase file in order to use some of the v2 engine functionality.   So far this seems to be working as well.

**Comment by beave** [comment]
awesome thanks
