### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by bhennigar** [beave/sagan#70]
I'm receiving a new error when running 'make' with the latest code in git. This is using the code committed after [issue 69](https://github.com/beave/sagan/issues/69). When using the previous commit from June 15 (8100fb09936931095dd1adca6bae4b6decdf324e), Sagan will install when using the workaround in [issue 68](https://github.com/beave/sagan/issues/68) but not run in daemon mode - [issue 69](https://github.com/beave/sagan/issues/69)
Received the same error when attempting to install on Ubuntu server 14.04 x64 and Debian 8.5 x64.

----

make
make  all-recursive
make[1]: Entering directory '/root/code/sagan'
Making all in src
make[2]: Entering directory '/root/code/sagan/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I/usr/local/include/libfastjson  -I/usr/local/include  -I/usr/local/include/ -I/usr/local/include/  -g -O2 -MT sagan-sagan.o -MD -MP -MF .deps/sagan-sagan.Tpo -c -o sagan-sagan.o `test -f 'sagan.c' || echo './'`sagan.c
In file included from sagan.c:72:0:
sagan-plog.h:33:20: error: unknown type name ‘_SaganSigArgs’
 void plog_handler( _SaganSigArgs * );
                    ^
sagan.c: In function ‘main’:
sagan.c:499:62: error: ‘plog_handler’ undeclared (first use in this function)
             rc = pthread_create( &pcap_thread, NULL, (void *)plog_handler, NULL );
                                                              ^
sagan.c:499:62: note: each undeclared identifier is reported only once for each function it appears in
Makefile:556: recipe for target 'sagan-sagan.o' failed
make[2]: *** [sagan-sagan.o] Error 1
make[2]: Leaving directory '/root/code/sagan/src'
Makefile:378: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/code/sagan'
Makefile:318: recipe for target 'all' failed
make: *** [all] Error 2

-----

**Comment by beave** [comment]
Hey - Are you using plog mode?  I'm wondering if it's related to the --daemon issue you are seeing. 

This should correct that compile time error. Please let me know!  Thank you.

**Comment by beave** [comment]
I believe this compile issues has been fixed.
