### ISSUE TITLE
meta_content can not use depth,distance,etc. and can not mix depth,distance,etc. with meta_content and content

### ISSUE THREAD

**Issue by red8383light** [beave/sagan#73]
Does not appear that you can use depth, distance, etc. with meta_content.  When searching for 'Account Name:', it does not appear to honor a distance to allow me to search for a second 'Account Name:' after the first 'Account Name:'.  Also, there does not appear to be a way to integrate both content with meta_content so that I can define a depth in content and a distance for meta_content after the content.

**Comment by beave** [comment]
Added meta_depth, meta_within, etc for the 1.1.1 release.  Closing this.  Still would be nice if content and meta_content options (within/meta_within) played better together.
