### ISSUE TITLE
Feature Request Dynamic Rule sets

### ISSUE THREAD

**Issue by red8383light** [beave/sagan#74]
If Sagan had a way to determine a fingerprint of a log type and determine the rule set that the event should be detected in and enable that rule set if the set is not already enabled.  This could allow Sagan to enable specific rule sets if a new application was installed on a device and a specific rule set was available for it but not enabled currently.

**Comment by beave** [comment]
This is a long term goal.  Probably won't make it into 1.1.2,  but under consideration.

**Comment by beave** [comment]
This has been committed.  It works like this.  There is a new "processor" called "dynamic_load" in Sagan.  It uses this format:

processor dynamic_load: sample_rate=1000 type=dynamic_load

The "sample_rate" is how often to check logs for "new" activity.  The "type" tells it what to do upon detecting "new" logs.  Valid types are "dynamic_load" (log to sagan.log,  u2 and load the rule set for the new logs),  "log_only" (only write to the sagan.log) and "alert" (only write to u2).  

There is a new rule option that ties to this.  It is called "dynamic_load".  This tells Sagan that a) the rule is a dynamic rule and should follow what the processor tells it to do (type/sample_rate) b) what ruleset to load if it is triggered.  For example: 

alert syslog $EXTERNAL_NET any -> $HOME_NET any (msg: "[DYNAMIC] Proftp logs detected via program."; program: proftpd; dynamic_load: $RULE_PATH/proftpd.rules; classtype: dynamic-rules; reference: url,wiki.quadrantsec.com/bin/view/Main/5003022 sid:5003022; rev:1;)

When the program "proftpd" is detected in a sample,  Sagan will automatically load,  if the type is set,  the $RULE_PATH/proftpd.rules. 

This is in testing and on github.
