### ISSUE TITLE
Feature Request Dynamic meta_contents

### ISSUE THREAD

**Issue by red8383light** [beave/sagan#75]
If you could create a variable 'VAR DC file://servers.txt' that sagan could create a meta_content based off of what it pulled from a file, and then change the variable to include the updated content of the variable.  An example being tracking all DC's for a particular event and when a new DC start's sending logs, a side script could detect the new log entry, update the servers.txt file, and then sagan could update the 'DC' variable which would now include the new server and it would dynamgically be added to the rule.  This should also help greatly reduce meta_contents and possible contents if their variable can just be dynamically changed rather than having to always change the rule to include a new content or meta_content.

**Comment by beave** [comment]
Let's implement this in 1.1.2

**Comment by beave** [comment]
This has been added.  Needs to be tested,  but pretty straight forward.

**Comment by beave** [comment]
Actually,  i'm going to go ahead and close this out..  You can now do:

var MYVAR somevalue
var MYVAR [a, list, of, values]
var MYVAR file:/path/to/my/values.txt

**Comment by red8383light** [comment]
I see it takes in the file, but does Sagan check the file to see if it has changed, and if so, update the variable?  Idea being, I have some script looking for a 4728 event and for group Administrator.  If it sees that, it takes that user name and adds it to the file.  I need Sagan at some point to recheck that variable and then update the variable contents if a difference is detected.  Maybe something like:
var MYVAR file:/path/to/file.txt 12
Sagan would save the md5 of this file and recheck every 12 hours.
If it noticed a difference, it will overwrite the old variable with the newly ingested variable.

**Comment by beave** [comment]
Negative.  If your script is doing the updating, then it can issue a kill -HUP (reload),  which will cause Sagan to read in the new values :) See what I mean?

**Comment by red8383light** [comment]
Yes, that makes since.  Good point!


Sent via the Samsung Galaxy Note7, an AT&T 4G LTE smartphone
-------- Original message --------From: Champ Clark <notifications@github.com> Date: 9/29/16  9:51 PM  (GMT-05:00) To: beave/sagan <sagan@noreply.github.com> Cc: Adam Hall <red8383light@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [beave/sagan] Feature Request Dynamic meta_contents (#75) 
Negative.  If your script is doing the updating, then it can issue a kill -HUP (reload),  which will cause Sagan to read in the new values :) See what I mean?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/beave/sagan","title":"beave/sagan","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/beave/sagan"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beave in #75: Negative.  If your script is doing the updating, then it can issue a kill -HUP (reload),  which will cause Sagan to read in the new values :) See what I mean?\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/beave/sagan/issues/75#issuecomment-250639307"}}}
