### ISSUE TITLE
Format of HOME/EXTERNAL NET vars

### ISSUE THREAD

**Issue by CyberTaoFlow** [beave/sagan#77]
Greetings!

I tried to set the HOME_NET variable using CIDR notation as done in snort ( [ 172.16.0.0/12,192.168.0.0/16,10.0.0.0/8] ) and was unable to start.  Each time I received the error
[E] [10/17/2016 11:57:21] - [E]: Invalid IP 172.16.0.0/12 in your config file var declaration!

Sagan then quit quietly.  Looking at the RFC1918 var I decided to try to use that setting 
var HOME_NET $RFC1918
This time sagan started but had the following errors;
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[*] [10/17/2016 12:09:40] - Loading /etc/sensor/sagan-rules/custom.rules rule file
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 339] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[*] [10/17/2016 12:09:40] - Loading /etc/sensor/sagan-rules/attack.rules rule file
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...
[W] [10/17/2016 12:09:40] - [sagan-rules.c, line 428] Value is not a valid IP '$RFC1918'
[W] [10/17/2016 12:09:40] - Warning: Got a inet_pton() error for "$RFC1918" but continuing...

What is the correct format for using EXTERNAL and HOME_NET?

**Comment by beave** [comment]
Let me look into it and get back with you.  It doesnt look like it's translating the $RFC1918 var to its value.  When you hardcode in a value,   does it work?  Like:

var HOME_NET [10.0.0.0/8]

**Comment by CyberTaoFlow** [comment]
I did not try just one subnet ill try that and get back

**Comment by beave** [comment]
I got a chance to test this.   I committed a fix for it.  Let me know how it works out.

**Comment by beave** [comment]
I should point out, this should work as well:

var HOME_NET $RFC1918

**Comment by beave** [comment]
?
