### ISSUE TITLE
Var issue with update 1.1.3 

### ISSUE THREAD

**Issue by disputed1** [beave/sagan#78]
The following section needs to be dropped down or it causes breakage. sagan.conf

var SSH_PORT 22
var HTTP_PORT 80
var HTTPS_PORT 443
var TELNET_PORT 23
var DNS_PORT 53
var SNMP_PORT 161
var POP3_PORT 110
var IMAP_PORT 143
var SMTP_PORT 25
var MYSQL_PORT 3306
var MSSQL_PORT 1433
var NTP_PORT 123
var OPENVPN_PORT 1194
var PPTP_PORT 1723
var FTP_PORT 21
var RSYNC_PORT 873
var SQUID_PORT 3128

[E] [11/15/2016 20:28:51] - [sagan-rules.c, line 507] Invalid destination port on line 37 in /usr/local/etc/sagan-rules/openssh.rules

**Comment by beave** [comment]
Found this.  I'll have a fix for it in the AM.   Likely needs to be corrected in a couple of places.

**Comment by beave** [comment]
Fixed.  Not sure if I like it though.

**Comment by disputed1** [comment]
Woop nice job. I'm curious about the fix, get with you in the AM about it
