### ISSUE TITLE
Dynamic ssh-tectia-server .rules.rules

### ISSUE THREAD

**Issue by disputed1** [beave/sagan#79]
[sagan-rules.c, line 181] Cannot open rule file (/usr/local/etc/sagan-rules/ssh-tectia-server.rules.rules - No such file or directory)

suggest correcting to /usr/local/etc/sagan-rules/ssh-tectia-server.rules to correct call 

thank you!

**Comment by beave** [comment]
fixed

**Comment by disputed1** [comment]
Ty
