### ISSUE TITLE
email output inconsistent with configuration

### ISSUE THREAD

**Issue by Brian-Echeverry** [beave/sagan#83]
email output sending ping events to example address (example.com) after removal from yaml config and custom address being added to rules. Emails are going to the address assigned in each rule as expected as well.

**Comment by beave** [comment]
This should be fixed.  Please test.

**Comment by Brian-Echeverry** [comment]
Thanks Champ, I'll take a look as soon as I get in.Brian EcheverryDeployment Lead / Senior Security EngineerQuadrant Information Security 4651 Salisbury Road, Suite 185 | Jacksonville, FL 32256O: (904) 296-9100 x121M: (864) 421-4757becheverry@quadrantsec.comOn Mar 7, 2017 11:44 PM, Champ Clark <notifications@github.com> wrote:This should be fixed.  Please test.
