### ISSUE TITLE
Source and Destination Ports in Rules not Matched against Logs

### ISSUE THREAD

**Issue by YoichSec** [beave/sagan#84]
I noticed this behavior while testing out the xbit updates I promised. In the first part of Sagan's snort-like rules, e.g. $EXTERNAL_NET any -> $HOME_NET 22, the IP addresses or networks are matched against incoming log messages as expected. The rule will only trigger if the IP addresses in the log messages conform to the addresses or networks in the rule. However, the ports are not matched against the logs and only serve as an optional setting to specify a source or destination port for the Sagan alert when log normalization fails or is not performed. This is apparently by design because check-flow.c where the matching occurs doesn't handle ports. However, I think matching the ports would be beneficial and is the more generally expected behavior. Is there a reason this is not currently done? If not, I could potentially give this a shot myself.

**Comment by beave** [comment]
In the original design of Sagan,  $EXTERNAL_NET and $HOME_NET where not used at all.   The protocol (syslog,tcp,udp.icmp) and ports are automatically applied.   The idea is to "line up" data as close to possible with other sources.   This way,   if we see a message from "OpenSSH" we can safely assume the protocol will be TCP and on port $SSH_PORT.   Normalization can over ride this if needed.   

By aligning the data with things like IDS,  if we search for "all traffic related to TCP port 22" we'll get both logs and packet data.   So, unlike IDS,  we apply this information to the log message rather than using it as a filter.  

Later on Adam Hall wrote the code for "flow checking".  You are correct in how it works.   It only applies rules to matching source/network traffic.   The idea is like this:

I can create a variable named "var $WINDOWS_SERVERS [192.168.1.0/24]".   I could then apply that to my windows-*.rules.    This leads to less CPU usage and you're targeting only the network segment with the rules you want.

In retrospect, the $HOME_NET/$EXTERNAL_NET is sort of confusing and I've not see it used very often.   On the other hand application of the protocol/port information has been extremely useful.   It makes aligning the data really easy.  

If anything,  I'd rather see $HOME_NET/$EXTERNAL_NET handling moved as a rule option.  The issue with that is that we'd still be in the same boat.  

If we where to move it to your suggested behavior,   I'd still need to supply that data somewhere.   It would have to become a rule option (default_protocal: tcp;  default_port: $SSH_PORT) (??).   On the other hand,   it might be possible to move your suggested behavior to a rule options as well ?  

Let me ponder on it a bit and let me know your thoughts..   Thanks.

**Comment by YoichSec** [comment]
I see the ports serve a vital purpose as is. Thanks for clarifying. For me, when I first started working with Sagan rules, I made assumptions on which parts were "conditions" and which parts were "actions" or "outputs" based on their corresponding functions in Snort rules. Since you keep the same Snort format but some "condition" fields became "output" fields, I needed to understand the source code to work out where all the differences were. So my most logical choice would be to make the entirety of the flow specification (proto ip:port->ip:port) a rule condition and add default port specification as a rule option. However, that's a design decision and is entirely up to you, of course. I should note that the reason I have this perspective as well as the desire for port matching is tied to the fact that I work much more with network sensors than with host logs. In a typical SIEM-like setup analyzing mostly host logs, this would call for a lot of rules that start with (any any:any->any:any). I could implement this on the side if general demand does not exist. Thanks.

**Comment by beave** [comment]
You do bring up a valid point.  I just need to ponder on it a little bit.   Moving the proto/port information as a rule option wouldn't be terribly difficult to do.   Modifying the rules would be a PITA,  but it is what it is.   Not a big deal,  just tedious.  

It would put the Sagan rules more "in line" with the Snort syntax which is a design goal. 

I doubt it would be used a lot, but in situation where it was needed,  it might be useful.  It would largely depend (I imagine) on successful normalization.

Let me think and chat with some people back at the office.

**Comment by YoichSec** [comment]
I definitely agree with the hesitation of changing the meaning of existing rules. On the other hand, I'd be surprised if I'm the only one who wrote rules assuming the ports and protocol were filter conditions. I certainly wouldn't be changing the existing rules by hand. Maybe a few lines of ugly bash could do the trick.

As another side note, the ports as a filter condition would be most useful with the support of port group variables like in Snort. Since the ports in Sagan are meant as an output, only single-value port variables are currently supported in Sagan. So there would be a bit more work necessary to get port filtering in Sagan working like it does in Snort.

**Comment by beave** [comment]
I've talked with some guys at my office and they seem to lean towards your suggestion.    People at our SOC even brought how we use 'content:!" when dealing with port issues.    I'm leaning towards the change myself but let me ponder on it a little bit more.    Move the protocol and ports to rule options would probably look like:

default_proto: tcp; 
default_src_port: 80; 
default_dst_port: 80 

That would be easy enough.   Let me know your thoughts.   Again,  I'm leaning towards the change,  but want to ponder a bit more before "jumping in".  I appreciate the time & discussion about this.

**Comment by beave** [comment]
After mulling it over and chatting with some people,   it is the consensus that this is right direction to go.   Here's the best way I think we should go about it: 

- I'd like to QA what we've got right now and "freeze" it for the next release (version 1.1.6).   If all goes well (no major memory leaks, build issues, etc), this shouldn't take to long.   Shoot for a "release" of early next week.   I'll get this started today.

- I figure I can move and add the "default_protocol",  "default_src_port" and "default_dst_port" options.    That shouldn't be difficult to do.

- Right after I get those new rule options in place,  you can start work on the other side of things.  This way,  we're less likely to have conflicts.  

Let me know what you think.   I'm looking forward to it!

**Comment by beave** [comment]
Build tests are fine.  Minor issue with Clang,  but nothing big.    I've got it running on some test env. now.  Will see how it survives the weekend.  Have a good one man!

**Comment by YoichSec** [comment]
Thanks! I think your suggested design is spot-on. Let me know if you need anything from me.

**Comment by beave** [comment]
We found an issue while testing that I'm trying to correct.  It involves 

content:!
meta_content:!

Soon as I'm done with that and another round of testing,  we should be good.

**Comment by beave** [comment]
Oh - should point out,  it has nothing to do with your code.   This is on me.

**Comment by beave** [comment]
Ok - back in business.   Starting up new testing!

**Comment by YoichSec** [comment]
Thanks for the updates!

**Comment by beave** [comment]
Released 1.1.6 today.  We should be set to move forward now.   I'll take care of moving the port/proto options into the rule options.   You still want to tackle the other stuff?

**Comment by YoichSec** [comment]
Works for me. Do you have a target date in mind? I have some possible work travel coming up and wouldn't want to hold you guys up.

**Comment by beave** [comment]
No, there is no target date at this time.   It would be great if it could be completely/testing in a month or so.  I've already made the "default_protocol", "default_src_port" and "default_dst_port" changes but left the legacy stuff in place.  I'll push that up ASAP!  Probably this afternoon.

From there,  you can do a pull and start work on your side.  I'm going to be doing a lot of JSON related stuff which shouldn't cause any issues. 

I'll post here after I push that new code ("default_protocol", etc. rule options).

**Comment by YoichSec** [comment]
Sounds good. I'll watch for it.

**Comment by beave** [comment]
Pushed the code up.  Sorry for the delay!

**Comment by beave** [comment]
I think you are set to go!

**Comment by YoichSec** [comment]
Got it!
By the way, I see something odd in part of the code that I need to change:
`if ( netcount == 6 ) {

                //dst_port = config->sagan_port;				/* Set to default */

                if (strcmp(nettmp, "any")) {
                    dst_port = atoi(nettmp);	/* If it's _NOT_ "any", set to default */
                }

                if (Is_Numeric(nettmp)) {
                    dst_port = atoi(nettmp);		/* If it's a number (see Sagan_Var_To_Value),  then set to that */
                }

                if ( dst_port == 0 ) {
                    Sagan_Log(S_ERROR, "[%s, line %d] Invalid destination port on line %d in %s", __FILE__, __LINE__, linecount, ruleset_fullname);
                }

                rulestruct[counters->rulecount].dst_port = dst_port;	/* Set for the rule */
            }

`
The current parsing for source and destination port looks like this.
Shouldn't that first nested if statement be "if it IS 'any', set to the default", where default is config->sagan_port which is already its value? At this point nettmp should be 'any' or numeric, so I'm not sure what it's meant to handle. It will need to be changed anyway, but I just want to make sure. Thanks.

**Comment by beave** [comment]
That was a recent change.  The idea was to go ahead and set the dst_port to the default.  If the is _not_ "any",  then set it to it's value.   This was something I did the other night.  :(

I'll change it shortly.   It was pretty late when i was adding this in :)

**Comment by beave** [comment]
Yeah - so i re-looked.   The dst_port is being set prior to any checks.   This way,  if it is set to "any",  its technically already set.   If it is _not_ set to "any",  we set it to the user supplied value.    That make sense?  I believe you're going to have to rip it all out anyways :)

**Comment by YoichSec** [comment]
Makes sense with the caveat that any numeric value would have been set in the next if statement and any non-numeric value that's not 'any' shouldn't exist since variables would have been replaced by their values. But yes, it will need to be ripped out anyway :)
I'll get started on that shortly.

**Comment by YoichSec** [comment]
I'm implementing this in pieces:

1. Port checking (Done)
2. Separate handling of new rule options from original port and protocol specifications (Done)
3. Add protocol checking
4. Add support for port not equal to
5. Add support for port ranges
6. Add support for port groups with multiple ranges or values
7. Script to modify existing rules to comply with new rule structure

**Comment by beave** [comment]
I've been knocking out the __thread,  but a lot of the functions depend on returns.   I've been leaving those return values in there. 

With this in mind,  I think you can safely continue work since I'm not trying to (yet) change core functionality.  I'm simply trying to get rid of __thread stuff..  I'll return back on the return verses void stuff later.

**Comment by beave** [comment]
OK!  I just did pretty large commits which take care of all code inconsistence issues!  You should be 100% good to go now.  I'm moving over to JSON output and Redis....... :)

**Comment by YoichSec** [comment]
Cool. Thanks!

**Comment by YoichSec** [comment]
OK it took some time to bring everything up to date with the new formatting style, but I have parts 1-3 done and tested. Would you rather do one big pull when it's all done or check the first part now? What's done is basic port and protocol checking and the handling of default protocols and ports. What I'd like to add still is port groups, !ports, and support for multiple port ranges.

**Comment by beave** [comment]
I think on big pull would be better.  It might get confusing to "see" the direction without the parts there.  

Sounds awesome man!

**Comment by YoichSec** [comment]
OK I made and tested the edits, but there are some conflicts in the pull request due to formatting changes. Unfortunately git hasn't done a great job at matching up the old with the new and so I may have to pull the new updates and retest before creating another pull request.

**Comment by YoichSec** [comment]
OK I got rid of all the conflicts and re-tested. The formatting follows the old style, so if you have a quick way of doing the astyle updates that would probably be best.

**Comment by beave** [comment]
Still testing.  I'm also out of town on business.  Just wanted to let you know I'm still on this :)

**Comment by YoichSec** [comment]
No problem. Thanks for the update.

**Comment by beave** [comment]
Merged.    I'm going to go ahead and close this.
