### ISSUE TITLE
FIFO sizeproblem

### ISSUE THREAD

**Issue by Fadavvi** [beave/sagan#94]
Hi,
I installed Sagan 1.1.8-git on Ubuntu 16.4 (4.4.0-21-generic). 
cat /proc/sys/fs/pipe-max-size  ==> 1048576
fifo-size: 1048576 ==> ( in core section of /usr/local/etc/sagan.yaml)
I ran Sagan with [ sagan --config /usr/local/etc/sagan.yaml -u anpsec ]. 
Last massages on screen: 
      [*] Attempting to open syslog FIFO (/var/sagan/fifo/sagan.fifo).
      [*] Successfully opened FIFO (/var/sagan/fifo/sagan.fifo).
      [*] FIFO capacity is -1 bytes.  Changing to 1048576 bytes.
      [W] FIFO capacity could not be changed.  Continuing anyways...
      [W] FIFO writer closed.  Waiting for FIFO writer to restart....
and program wait for a long time without restarting anything. 
Can you help me for resolve this problem??
BR,
Milad
[sagan.log.txt](https://github.com/beave/sagan/files/1090391/sagan.log.txt)

**Comment by beave** [comment]
Did you get this worked out?  The writer needs to be up first (syslog-ng/rsyslog).  

Anyways,  hope it worked out but let me know if you're still having issues.

**Comment by Fadavvi** [comment]
Yes, I just ran the program with a normal user and problem resolved. 
Thanks for your attention.
