### ISSUE TITLE
Typo in src/liblognormalize.c

### ISSUE THREAD

**Issue by CyberTaoFlow** [beave/sagan#95]
line 224 has 
ash-md5 instead of hash-md5

**Comment by beave** [comment]
Doh!  Thank you.  Will correct asap.On Jul 9, 2017 2:09 AM, Psipher Diaz <notifications@github.com> wrote:line 224 has
ash-md5 instead of hash-md5

**Comment by beave** [comment]
Nice catch and thanks again.   It has been corrected.
