### ISSUE TITLE
No Any Event Generated

### ISSUE THREAD

**Issue by Fadavvi** [beave/sagan#96]
Hi Dear Sagan Team,
I installed Sagan 1.1.8-git on Ubuntu 16.4 (4.4.0-21-generic) and we used rsyslog. 
I installed Sagan and everything else! System receive Syslog UDP massages on port 514 than I configure in Sagan config file. ( I checked it out by TCPDUMP) But No event generated! ( I simulate "Successfully SSH password guessing" Attack. ) This is my confs and log file.
[sagan.yaml.txt](https://github.com/beave/sagan/files/1133707/sagan.yaml.txt)
[barnyard2.conf.txt](https://github.com/beave/sagan/files/1133709/barnyard2.conf.txt)
[sagan.log (2).txt](https://github.com/beave/sagan/files/1133712/sagan.log.2.txt)
( Other files : unified2.alert.XXXXXX // eve.json // alert.log are empty )
Where is wrong ??! What should I do ?? 
I know this is not an issue but I didn't find any email address. Sorry about this.
BR,
Milad

**Comment by beave** [comment]
No problem.  Sagan has several --debug modes.   Try "--debug syslog" which will display any and all data Sagan receives.    Let's start there and work our way back :)

Keep in mind,  you'll need a syslog daemon like syslog-ng or rsyslog to "feed" Sagan.

Also see https://wiki.quadrantsec.com/bin/view/Main/SaganInstall

**Comment by Fadavvi** [comment]
I used rsyslog with this config 
[rsyslog.conf.txt](https://github.com/beave/sagan/files/1134535/rsyslog.conf.txt)
and ran mkfifo and change owner and permissions like below: 
![image](https://user-images.githubusercontent.com/21213484/28004598-fbc99fe2-655a-11e7-822c-4e5b4c60ceab.png)
Then I ran Sagan with in syslog debugging mode. But still nothing!
BR and thanks for your time ,
Milad

**Comment by Fadavvi** [comment]
After waiting for 15 min problem resolved and Sagan received Syslog massages and generate events. Thanks for your time. but I have another question! I send all logs to Graylog then forwarded to Sagan. and I still don't get any Bro IDS log than a sent to Graylog. Is there a "should" for send logs directly to Sagan?? Or any suggestion ??

**Comment by beave** [comment]
In the future,  to speed up the debugging process,  you can use the "logger" command to create syslog messages.  

Sagan only receives data.  It does not send any data.    This means your syslog daemon (rsyslog) show take the logs and send it to both Graylog and Sagan.    The same should apply for Bro logs.   That's a log routing issue which is outside the scope of Sagan. 

Also - in the future you can e-mail the Sagan mailing list for help.    You'll likely get help faster that way.  The mailing list is at: https://groups.google.com/forum/#!forum/sagan-users
